valid = {
    confirm: "ยืนยัน",
    cancel: "ยกเลิก",
    no_data: "-",
    preview: "แสดงตัวอย่าง",
    Please_signIn: "กรุณาเข้าสู่ระบบ",
    overpage: "cannot go to over page",
    less_2char: "กรุณากรอกอย่างน้อย 2 ตัวอักษร",
    less_3char: "กรุณากรอกอย่างน้อย 3 ตัวอักษร",
    less_4char: "กรุณากรอกอย่างน้อย 4 ตัวอักษร",
    less_5char: "กรุณากรอกอย่างน้อย 5 ตัวอักษร",
    less_6char: "กรุณากรอกอย่างน้อย 6 ตัวอักษร",
    less_9char: "กรุณากรอกอย่างน้อย 9 ตัวอักษร",
    less_10char: "กรุณากรอกอย่างน้อย 10 ตัวอักษร",
    more_50char: "กรุณากรอกไม่เกิน 50 ตัวอักษร",
    more_10char: "กรุณากรอกไม่เกิน 10 ตัวอักษร",
    more_5char: "กรุณากรอกไม่เกิน 5 ตัวอักษร",
    min_4_max_12char: "กรุณากรอกอย่างน้อย 4 ตัวอักษรและไม่เกิน 12 ตัวอักษร",
    min_4_max_16char: "กรุณากรอกอย่างน้อย 4 ตัวอักษรและไม่เกิน 16 ตัวอักษร",
    min_4_max_20char: "กรุณากรอกอย่างน้อย 4 ตัวอักษรและไม่เกิน 20 ตัวอักษร",
    min_6_max_12char: "กรุณากรอกอย่างน้อย 6 ตัวอักษรและไม่เกิน 12 ตัวอักษร",
    min_6_max_20char: "กรุณากรอกอย่างน้อย 6 ตัวอักษรและไม่เกิน 20 ตัวอักษร",
    confirm_del: "Confirm to delete this item. ",
    confirm_del_all: "Confirm to delete all item. ",
    confirm_restore: "Confirm to restore this item. ",
    confirm_restore_all: "Confirm to restore all item. ",
    Notice_del: "กรุณาเลือกข้อมูลที่ต้องการลบ",
    drag_to_junk: "ลากลงถังขยะ ",
    save_success: "บันทึกสำเร็จ",
    save_Unsuccess: "บันทึกข้อมูลไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
    can_save: "สามารถทำการบันทึกได้",
    cannot_save: "ไม่สามารถทำการบันทึกได้",
    Edit_success: "แก้ไขข้อมูลเรียบร้อย",
    Edit_Unsuccess: "แก้ไขข้อมูลไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
    del_success: "ลบข้อมูลเรียบร้อย",
    del_Unsuccess: "ลบข้อมูลไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
    add_success: "เพิ่มเสร็จสมบูรณ์",
    all_required: "กรุณากรอกข้อมูลให้ครบทุกช่อง",
    cannot_check_info: "ไม่สามารถตรวจสอบข้อมูลได้ กรุณาลองใหม่อีกครั้ง",
    img_fix5: "เลือกได้เพียง 5 รูปภาพ เท่านั้น",
    required: "กรุณากรอกข้อมูล",
    Pname_already: "ชื่อสินค้าซ้ำ",
    Pgroup_already: "ชื่อกลุ่มสินค้าซ้ำ",
    Max_Word5: "กรอกสูงสุด 5 คำ",
    formaterror: "กรุณาตรวจสอบรูปแบบข้อความ",
    compare_exist: "คุณเลือกสินค้าเปรียบเทียบซ้ำ ",
    compare_choose: "กรุณาเลือกสินค้าที่ต้องการเปรียบเทียบ ",
    compare_max: "จำนวนสินค้าเปรียบเทียบเต็ม ",
    input_correct_number: "กรุณากรอกตัวเลขให้ถูกต้อง",
    fix_format_picture: "คุณสามารถเลือกได้เฉพาะไฟล์ .jpg .jpeg .gif .png เท่านั้น",
    fix_format_number: "กรอกได้เฉพาะตัวเลขเท่านั้น",
    fix_format_email: "กรุณากรอกรูปแบบอีเมล์ให้ถูกต้อง",
    add_buylead_success: "บันทึกการประกาศซื้อสำเร็จ",
    select_district: "กรุณาเลือกอำเภอ/เขต",
    select_province: "กรุณาเลือกจังหวัด",
    select_Country: "กรุณาเลือกประเทศ",
    valid_BuyleadExpire: "วันที่สิ้นสุดประกาศซื้อต้องมากกว่าวันที่ปัจจุบัน",
    cannot_insert_zero: "ไม่สามารถเลือกให้น้อยกว่า 0 ได้",
    Ismaxproduct: "เต็ม! คุณสามารถเพิ่มสินค้าได้สูงสุด 20 รายการ กรุณาอัพเกรดเพื่อรับสิทธิเพิ่มเติม",
    Input_keyword: "กรุณาระบุคำค้น",
    same_value: "กรุณากรอกข้อมูลรหัสผ่านให้ตรงกัน",
    Pass_not_same: "รหัสผ่านไม่ตรงกัน",
    User_incorrect: "บัญชีผู้ใช้ถูกระงับการใช้งาน",
    password_incorrect: "รหัสผ่านไม่ถูกต้อง",
    Change_password_error: "เปลี่ยนรหัสผ่านผิดพลาด กรุณาลองใหม่อีกครั้ง",
    request_unsuccessful: "การร้องขอไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
    Please_unlock: "กรุณากรอก Username หรือ Email Address ที่ได้ลงทะเบียนกับระบบไว้",
    selectJobCate: "เลือกหมวดหมู่งาน",
    selectJobtype: "เลือกประเภทงาน",
    selectReqEducation: "เลือกระดับการศึกษา",
    selectReqExp: "เลือกประสบการณ์",
    selectAttributes: "เลือกคุณสมบัติที่ต้องการ",
    selectBiztype: "เลือกประเภทธุรกิจ",
    selectComplevel: "เลือกระดับสมาชิก",
    selectServicetype: "เลือกประเภทการใช้งาน",
    selectArticletype: "เลือกประเภทบทความ",
    selectBank: "เลือกธนาคาร",
    selectAcctype: "เลือกประเภทบัญชี",
    NoUserEmail: "ผู้ใช้หรืออีเมล์นี้ไม่อยู่ในระบบ",
    NoUser: "ชื่อผู้ใช้นี้ไม่มีอยู่ในระบบ",
    User_request: "ผู้ใช้นี้ไม่ตรงกับการร้องขอ",
    Email_request: "อีเมล์นี้ไม่ตรงกับการร้องขอ",
    NoEmail: "อีเมล์นี้ไม่อยู่ในระบบ",
    UserName_Exists: "ผู้ใช้นี้มีอยู่ในระบบ",
    Email_Exists: "อีเมล์นี้มีอยู่ในระบบ",
    UserNameNoEng: "รูปแบบชื่อผู้งานไม่ถูกต้อง (ภาษาอังกฤษเท่านั้น)",
    EmailNoEng: "รูปแบบอีเมล์ไม่ถูกต้อง (ภาษาอังกฤษเท่านั้น)",
    UserEmailNoEng: "ชื่อผู้ใช้หรืออีเมล์ไม่ถูกต้อง (ภาษาอังกฤษเท่านั้น)",
    CompName_Exists: "ชื่อบริษัทนี้มีอยู่ในระบบ",
    DisplayName_Exists: "ชื่อที่ใช้แสดงนี้มีอยู่ในระบบ",
    Change_pass_success: "เปลี่ยนรหัสผ่านเรียบร้อย",
    maximg_3: "สามารถอัพโหลดรูปภาพได้สูงสุด3รูปเท่านั้น",
    required_complete: "กรุณากรอกข้อมูลให้ครบถ้วน",
    details: "กรอกรายละเอียด",
    sendtoUser_success: "ส่งข้อมูลให้ลูกค้าเรียบร้อย",
    MessageLength: "ข้อความรายละเอียดโดยย่อของบทความยาวเกินไป กรุณาลองใหม่อีกครั้ง",
    required_img:"กรุณาเลือกรูปภาพ",
    //message
    enter_recipient: "กรุณากรอกชื่อผู้รับ",
    enter_subject: "กรุณากรอกหัวเรื่อง",
    enter_message: "กรุณากรอกเนื้อหาข้อความ",
    send_success: "การส่งข้อความเสร็จสมบูรณ์",
    draft_success: "บันทึกข้อความร่างสำเร็จ",
    mark_unread_success: "ทำเครื่องหมายยังไม่ได้อ่าน ประสบความสำเร็จ",
    del_msg_success: "ลบข้อความ ประสบความสำเร็จ",
    mark_importance_success: "ทำเครื่องหมายสำคัญ ประสบความสำเร็จ",
    mark_unimportance_success: "ทำเครื่องหมายไม่สำคัญ ประสบความสำเร็จ",
    fill_yourname: "กรุณากรอกชื่อของคุณ",
    fill_youremail: "กรุณากรอกอีเมล์ของคุณ",
    fill_yourmessage: "กรุณากรอกรายละเอียดข้อความของคุณ",
    enter_validemail: "รูปแบบอีเมล์ไม่ถูกต้อง (ภาษาอังกฤษเท่านั้น)",
    no_item_selected: "คุณยังไม่ได้เลือกรายการ",
    senddata_success: "ส่งข้อมูลให้ลูกค้าเรียบร้อยแล้ว",
    //purchasing
    Not_found_company: "ไม่พบบริษัทนี้",
    enter_search: "กรุณากรอกคำค้นหาของคุณ",
    compare_success: "เพิ่มสินค้าเปรียบเทียบสำเร็จ",
    //home
    search_product: "ชื่อสินค้า, คำค้นหาสินค้า",
    search_supplier: "ชื่อสินค้า, ชื่อผู้ขาย, คำค้นหาผู้ขาย",
    search_buylead: "ชื่อผู้ซื้อ, คำค้นหาประการซื้อ",
    specific: "ระบุ",
    non_specific: "ไม่ระบุ",
    hide_moredetail: "ซ่อนรายละเอียด",
    add_moredetail: "คลิ๊กเพื่อเพิ่มรายละเอียด",
    other: "อื่นๆ",
    please_select: "กรุณาเลือก",
    please_select_fav: "กรุณาเลือกรายการโปรด",
    select_all: "เลือกทั้งหมด",
    //Chat
    AlertMessage: " มีข้อความถึงคุณ",
    url_upload: "https://ouikumstorage.blob.core.windows.net/upload/",

    //Order
    BankID: "กรุณาเลือกธนาคารต้นทางของคุณ",
    BranchName: "กรุณากรอกข้อมูลสาขาที่ได้ทำการชำระเงิน",
    PayerAccName: "กรุณากรอกข้อมูลชื่อบัญชีผู้โอน",
    PayerAccNo: "กรุณากรอกข้อมูลหมายเลขบัญชีผู้โอน",
    //Buylead
    save_buyleadSuccess:"บันทึกเสร็จสมบูรณ์ กรุณารอการตรวจสอบจาก Admin"
}

// วิธีเรียกใช้ valid.cancel