valid = {
    confirm: "Confirm",
    cancel: "Cancel",
    no_data: "-",
    preview: "Preview",
    Please_signIn: "Please SignIn.",
    overpage: "cannot go to over page",
    less_2char: "Please enter at least 2 characters.",
    less_3char: "Please enter at least 3 characters.",
    less_4char: "Please enter at least 4 characters.",
    less_5char: "Please enter at least 5 characters.",
    less_6char: "Please enter at least 6 characters.",
    less_9char: "Please enter at least 9 characters.",
    less_10char: "Please enter at least 10 characters.",
    more_10char: "Please enter no more than 10 characters.. ",
    more_5char: "Please enter no more than 5 characters.. ",
    min_4_max_12char: "Please enter at least 4 char and no more than 12 char.",
    min_4_max_16char: "Please enter at least 4 char and no more than 16 char.",
    min_4_max_20char: "Please enter at least 4 char and no more than 20 char.",
    min_6_max_12char: "Please enter at least 6 char and no more than 12 char.",
    min_6_max_20char: "Please enter at least 6 char and no more than 20 char.",
    confirm_del: "Confirm to delete this item. ",
    confirm_del_all: "Confirm to delete all item. ",
    confirm_restore: "Confirm to restore this item. ",
    confirm_restore_all: "Confirm to restore all item. ",
    Notice_del: "Please select the data to be deleted.",
    drag_to_junk: "Drag to junk ",
    save_success: "Save has successfully ",
    save_Unsuccess: "Unsuccessful save data. Please try again later.",
    can_save: "Can be saved.",
    cannot_save: "Can not be saved.",
    Edit_success: "Edit successfully.",
    Edit_Unsuccess: "Unsuccessful edit data. Please try again later.",
    del_success: "Delete successfully.",
    del_Unsuccess: "Unsuccessful delete data. Please try again later.",
    add_succss: "Add has successfully",
    all_required: "Please fill in all required fields.",
    cannot_check_info: "Cannot check information, Please try again",
    img_fix5: "Just Select 5 Images Only",
    required: "This field is required.",
    Pname_already: "This productname have already",
    Pgroup_already: "This Groupname have already",
    Max_Word5: "fill max 5 words ",
    formaterror: "Your format is not correct. ",
    compare_exist: "This item has exist compare product. ",
    compare_choose: "Please choose product to compare. ",
    compare_max: "Compare products has full. ",
    input_correct_number: "Please input correct number.",
    fix_format_picture: "Support file .jpg .jpeg .gif .png only",
    fix_format_number: "Enter only numbers.",
    fix_format_email: "Enter a correct email address.",
    add_buylead_success: "Add buylead success.",
    select_district: "Please select district.",
    select_province: "Please select province.",
    select_Country: "Please select Country.",
    valid_BuyleadExpire: "Buylead expire date incorrect.",
    cannot_insert_zero: "Can not insert less than 0.",
    Ismaxproduct: "Full! You can add product to maximum 20 items. Please upgrade gold member for get more.",
    Input_keyword: "Please enter keyword",
    same_value: "Please enter the same value again.",
    Pass_not_same: "Passwords do not match.",
    User_incorrect: "Account was suspended.",
    password_incorrect: "Password is incorrect.",
    Change_password_error: "Change password error. Please try again later.",
    request_unsuccessful: "The request was unsuccessful. Please try again later.",
    Please_unlock: "Please unlock the security system.",
    selectJobCate: "Select a category.",
    selectJobtype: "Select job type.",
    selectReqEducation: "Select the level of education.",
    selectReqExp: "Select experience.",
    selectAttributes: "Select Attributes.",
    selectBiztype: "Please select a business type.",
    selectComplevel: "Please select a company level.",
    selectServicetype: "Please select a service type.",
    selectArticletype: "Please select a article type.",
    selectBank: "Please select Bank.",
    selectAcctype: "Please select a Account type.",
    NoUserEmail: "Username or email does not exist in the system",
    NoUser: "This user was not found in the system.",
    User_request: "This username does not match the request.",
    Email_request: "This email does not match the request.",
    NoEmail: "This Email was not found in the system.",
    UserName_Exists: "UserName exists.",
    Email_Exists: "Email exists.",
    UserNameNoEng: "UserName is incorrect (in English only).",
    EmailNoEng: "Email is incorrect (in English only).",
    UserEmailNoEng: "UserName or Email is incorrect (in English only).",
    CompName_Exists: "Company name exists.",
    DisplayName_Exists: "Display name exists.",
    Change_pass_success: "Change password successfully",
    maximg_3: "Can upload up to 3 images.",
    required_complete: "Please complete all required fields.",
    details: "Enter details.",
    sendtoUser_success: "Send data to Member successfully.",
    MessageLength: "A brief description of the article is too long. Please try again later.",
    required_img: "Please choose image",
    //message
    enter_recipient: "Please enter the recipient.",
    enter_subject: "Please enter a subject.",
    enter_message: "Please enter the message.",
    send_success: "Send message successfully.",
    draft_success: "Draft has been saved",
    mark_unread_success: "Mark Unread Successfully.",
    del_msg_success: "Delete Message Successfully.",
    mark_importance_success: "Mark Importance Successfully.",
    mark_unimportance_success: "Mark Unimportance Successfully.",
    fill_yourname: "Please fill in your name",
    fill_youremail: "Please fill in your email",
    fill_yourmessage: "Please fill in your message",
    enter_validemail: "Please enter a valid email address",
    no_item_selected: "You have not selected item",
    senddata_success: "Send data to customers successfully.",
    //purchasing
    Not_found_company: "Not found this company.",
    enter_search: "Please enter your search.",
    compare_success: "Add compare success",
    //home
    search_product: "search product",
    search_supplier: "search supplier",
    search_buylead: "search buylead",
    specific: "Specific",
    non_specific: "NonSpecific",
    hide_moredetail: "Hide more details.",
    add_moredetail: "Add more details.",
    other: "Other",
    please_select: "Please Select",
    please_select_fav: "Please Select Favorite",
    select_all: "Select All",
    url_upload: "https://ouikumstorage.blob.core.windows.net/upload/",
    //Buylead
    save_buyleadSuccess: "Save Success, Wait for admin approve" 
}
// วิธีเรียกใช้ valid.cancel