//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Benefit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Benefit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Benefit", typeof(Benefit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About B2BThai.
        /// </summary>
        public static string lblaboutWebsite {
            get {
                return ResourceManager.GetString("lblaboutWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the information as superior.
        /// </summary>
        public static string lblAccessInfo {
            get {
                return ResourceManager.GetString("lblAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิการเข้าถึงฟังก์ชั่นการทำงานของระบบ.
        /// </summary>
        public static string lblaccessrights {
            get {
                return ResourceManager.GetString("lblaccessrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name iNext step Co.,Ltd Saving Account.
        /// </summary>
        public static string lblAccname {
            get {
                return ResourceManager.GetString("lblAccname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name iNext step Co.,Ltd.
        /// </summary>
        public static string lblAccnameDesc {
            get {
                return ResourceManager.GetString("lblAccnameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบัญชีบริษัท โปรซอฟท์ ไอทีโอ จำกัด.
        /// </summary>
        public static string lblAccnameDesc1 {
            get {
                return ResourceManager.GetString("lblAccnameDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 980-2-06241-6.
        /// </summary>
        public static string lblAccno {
            get {
                return ResourceManager.GetString("lblAccno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250-6-02491-0.
        /// </summary>
        public static string lblAccno1 {
            get {
                return ResourceManager.GetString("lblAccno1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accounting software.
        /// </summary>
        public static string lblaccountsoftware {
            get {
                return ResourceManager.GetString("lblaccountsoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2571/1 Software resort Ramlhamheang
        ///Rd. Huamark Bangkrapi Bangkok 10240
        ///Tel: (02) 402-8067 
        ///Phone: (088) 258-3434.
        /// </summary>
        public static string lbladdrmapbkk {
            get {
                return ResourceManager.GetString("lbladdrmapbkk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 287 M.5 T. Sunsainoi Ampor.Sunsai
        ///Chiang Mai 50210
        ///Tel: (02) 402-8068
        ///Phone: (081) 359-7680.
        /// </summary>
        public static string lbladdrmapcm {
            get {
                return ResourceManager.GetString("lbladdrmapcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มประกาศซื้อสินค้าได้สูงสุด.
        /// </summary>
        public static string lbladdup {
            get {
                return ResourceManager.GetString("lbladdup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement-buying-selling.
        /// </summary>
        public static string lblAdsbuysell {
            get {
                return ResourceManager.GetString("lblAdsbuysell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิ์โฆษณาสินค้าในหน้าค้นหาสินค้า Hot Product.
        /// </summary>
        public static string lblAdsCate {
            get {
                return ResourceManager.GetString("lblAdsCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising with us Chick!.
        /// </summary>
        public static string lbladsclick {
            get {
                return ResourceManager.GetString("lbladsclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิ์โฆษณาสินค้าในหน้าแสดงข้อมูลรายละเอียดสินค้า Premium Product.
        /// </summary>
        public static string lblAdsFront {
            get {
                return ResourceManager.GetString("lblAdsFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิ์โฆษณาสินค้าในหน้าหลักของเว็บไซต์ Feature Product.
        /// </summary>
        public static string lblAdsHome {
            get {
                return ResourceManager.GetString("lblAdsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblAdsrate.
        /// </summary>
        public static string lblAdsrate {
            get {
                return ResourceManager.GetString("lblAdsrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please withholding tax on behalf of “Prosoft Comtech Co., Ltd.”.
        /// </summary>
        public static string lbladsrateaddr1 {
            get {
                return ResourceManager.GetString("lbladsrateaddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54/27 Ramkhamhaend 60/2 Ramkhamhaeng Huamark Rd. Bangkrapi Bangkok 10240.
        /// </summary>
        public static string lbladsrateaddr2 {
            get {
                return ResourceManager.GetString("lbladsrateaddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbladsrateaddr3 {
            get {
                return ResourceManager.GetString("lbladsrateaddr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the withholding tax document to the address below.
        /// </summary>
        public static string lbladsratecompany1 {
            get {
                return ResourceManager.GetString("lbladsratecompany1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2571/1 Software resort Ramkhamhaeng Rd. Huamark Bangkrapi Bangkok 10240.
        /// </summary>
        public static string lbladsratecompany2 {
            get {
                return ResourceManager.GetString("lbladsratecompany2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Company financial office).
        /// </summary>
        public static string lbladsratecompany3 {
            get {
                return ResourceManager.GetString("lbladsratecompany3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company will send the invoice and the receipt, after receive the original withholding tax only!.
        /// </summary>
        public static string lbladsratecompany4 {
            get {
                return ResourceManager.GetString("lbladsratecompany4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - For advertising rate please deduct 2% withholding tax and fax the deduction document to 089-967-6157 and send the original document by post to our address below.
        /// </summary>
        public static string lbladsratefee1 {
            get {
                return ResourceManager.GetString("lbladsratefee1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** New members must submit a copy of value added tax registration or a copy of company registration certificate with an address for billing purposes..
        /// </summary>
        public static string lbladsratefee2 {
            get {
                return ResourceManager.GetString("lbladsratefee2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Rates exclude VAT 7% and Bank transfer fee!.
        /// </summary>
        public static string lbladsratetax {
            get {
                return ResourceManager.GetString("lbladsratetax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วิธีชำระค่าโฆษณา.
        /// </summary>
        public static string lblAdvertisingPayment {
            get {
                return ResourceManager.GetString("lblAdvertisingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert you when there are any buying order.
        /// </summary>
        public static string lblalertorder {
            get {
                return ResourceManager.GetString("lblalertorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All help.
        /// </summary>
        public static string lblAllhelp {
            get {
                return ResourceManager.GetString("lblAllhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B shopping.
        /// </summary>
        public static string lblb2bshopping {
            get {
                return ResourceManager.GetString("lblb2bshopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home.
        /// </summary>
        public static string lblBacktoHome {
            get {
                return ResourceManager.GetString("lblBacktoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangkok.
        /// </summary>
        public static string lblBangkok {
            get {
                return ResourceManager.GetString("lblBangkok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become Fan Page.
        /// </summary>
        public static string lblbecomefanpage {
            get {
                return ResourceManager.GetString("lblbecomefanpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิ์ประโยชน์.
        /// </summary>
        public static string lblBenefits {
            get {
                return ResourceManager.GetString("lblBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramkhamheang 53 Rd..
        /// </summary>
        public static string lblbranch {
            get {
                return ResourceManager.GetString("lblbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขารามคำแหง 73.
        /// </summary>
        public static string lblbranch1 {
            get {
                return ResourceManager.GetString("lblbranch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมัครเพื่อขอใช้บริการ  Gold Member.
        /// </summary>
        public static string lblButton {
            get {
                return ResourceManager.GetString("lblButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประกาศซื้อ.
        /// </summary>
        public static string lblbuy {
            get {
                return ResourceManager.GetString("lblbuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 1 - Post Buying Request.
        /// </summary>
        public static string lblbuychapter1 {
            get {
                return ResourceManager.GetString("lblbuychapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 2 - Search Product.
        /// </summary>
        public static string lblbuychapter2 {
            get {
                return ResourceManager.GetString("lblbuychapter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 3 - Compare Product.
        /// </summary>
        public static string lblbuychapter3 {
            get {
                return ResourceManager.GetString("lblbuychapter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 4 - Request Price.
        /// </summary>
        public static string lblbuychapter4 {
            get {
                return ResourceManager.GetString("lblbuychapter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 5 - Contact to Supplier.
        /// </summary>
        public static string lblbuychapter5 {
            get {
                return ResourceManager.GetString("lblbuychapter5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 6 - Product Store.
        /// </summary>
        public static string lblbuychapter6 {
            get {
                return ResourceManager.GetString("lblbuychapter6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 7 - Purchase Center.
        /// </summary>
        public static string lblbuychapter7 {
            get {
                return ResourceManager.GetString("lblbuychapter7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer User Guide.
        /// </summary>
        public static string lblBuyerGuide {
            get {
                return ResourceManager.GetString("lblBuyerGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer Help.
        /// </summary>
        public static string lblbuyerhelp {
            get {
                return ResourceManager.GetString("lblbuyerhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiang Mai.
        /// </summary>
        public static string lblChiangMai {
            get {
                return ResourceManager.GetString("lblChiangMai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to choose web page theme.
        /// </summary>
        public static string lblchoosetheme {
            get {
                return ResourceManager.GetString("lblchoosetheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have more than 30 themes for you to use as your satisfaction Modern, Aesthetic and Satisfaction can be changes as needed..
        /// </summary>
        public static string lblchoosethemeDesc {
            get {
                return ResourceManager.GetString("lblchoosethemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or come see us.
        /// </summary>
        public static string lblcomeseeus {
            get {
                return ResourceManager.GetString("lblcomeseeus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company User Guide.
        /// </summary>
        public static string lblCompanyGuide {
            get {
                return ResourceManager.GetString("lblCompanyGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link a working function with.
        /// </summary>
        public static string lblConnectPostjob {
            get {
                return ResourceManager.GetString("lblConnectPostjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or contact sales and advertisement : 02-402-8413 or sale@AppStoreThai.com.
        /// </summary>
        public static string lblcontactsales {
            get {
                return ResourceManager.GetString("lblcontactsales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2013, AppStoreThai.com.
        /// </summary>
        public static string lblcopyright {
            get {
                return ResourceManager.GetString("lblcopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create website free.
        /// </summary>
        public static string lblcreatewebsitefree {
            get {
                return ResourceManager.GetString("lblcreatewebsitefree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer services : 02-402-8068, 081-359-7680 or support@AppStoreThai.com.
        /// </summary>
        public static string lblcustomerservice {
            get {
                return ResourceManager.GetString("lblcustomerservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        public static string lblcustomservice {
            get {
                return ResourceManager.GetString("lblcustomservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มสินค้าไม่จำกัด.
        /// </summary>
        public static string lblDisplaysproducts {
            get {
                return ResourceManager.GetString("lblDisplaysproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2BThaiExport.com allows you to add unlimited products The number of products you have, the more products you can display.
        /// </summary>
        public static string lblDisplaysproductsDesc {
            get {
                return ResourceManager.GetString("lblDisplaysproductsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display on the top.
        /// </summary>
        public static string lblDisplaytop {
            get {
                return ResourceManager.GetString("lblDisplaytop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold member you are very special customer as VIP level, we deliver you “the very first show of search results” and immediately give you the special right just update your product information regularly.
        /// </summary>
        public static string lblDisplaytopDesc {
            get {
                return ResourceManager.GetString("lblDisplaytopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All.
        /// </summary>
        public static string lblDownloadAll {
            get {
                return ResourceManager.GetString("lblDownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        public static string lblDownloadbuy {
            get {
                return ResourceManager.GetString("lblDownloadbuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member.
        /// </summary>
        public static string lblDownloadmember {
            get {
                return ResourceManager.GetString("lblDownloadmember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sell.
        /// </summary>
        public static string lblDownloadsell {
            get {
                return ResourceManager.GetString("lblDownloadsell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website.
        /// </summary>
        public static string lblDownloadwebsite {
            get {
                return ResourceManager.GetString("lblDownloadwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  App marketplace of Thailand.
        /// </summary>
        public static string lblE_market {
            get {
                return ResourceManager.GetString("lblE_market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive free several items.
        /// </summary>
        public static string lblExclusivefree {
            get {
                return ResourceManager.GetString("lblExclusivefree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manage your full business Get free! The shortcut tools that we selected for you either accounting software or job seeking website for 1 year free..
        /// </summary>
        public static string lblExclusivefreeDesc {
            get {
                return ResourceManager.GetString("lblExclusivefreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string lblFAQDesc {
            get {
                return ResourceManager.GetString("lblFAQDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After transferred, please FAX the Evidence (Pay-in-Slip).
        /// </summary>
        public static string lblfaxDesc1 {
            get {
                return ResourceManager.GetString("lblfaxDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and withholding tax to Ms. Thitima Jantha at FAX No.089-967-6157.
        /// </summary>
        public static string lblfaxDesc2 {
            get {
                return ResourceManager.GetString("lblfaxDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or email to sale@AppStoreThai.com or support@AppStoreThai.com.
        /// </summary>
        public static string lblfaxDesc3 {
            get {
                return ResourceManager.GetString("lblfaxDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblfaxDesc4 {
            get {
                return ResourceManager.GetString("lblfaxDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblfaxDesc5 {
            get {
                return ResourceManager.GetString("lblfaxDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX the evidence after transferred.
        /// </summary>
        public static string lblfaxtransfer {
            get {
                return ResourceManager.GetString("lblfaxtransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าหลักของเว็บไซต์ (Feature Product).
        /// </summary>
        public static string lblFeatureProduct {
            get {
                return ResourceManager.GetString("lblFeatureProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help to find the employee.
        /// </summary>
        public static string lblfindemployee {
            get {
                return ResourceManager.GetString("lblfindemployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person has become a human resource that very important to do any organization processes. Increase the chance to find the diligent employees. Just you easily post a job through www.lionjob.com and also to create a company brand to be known to outsiders.
        /// </summary>
        public static string lblfindemployeeDesc {
            get {
                return ResourceManager.GetString("lblfindemployeeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find job in thailand.
        /// </summary>
        public static string lblfindjob {
            get {
                return ResourceManager.GetString("lblfindjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string lblFirst {
            get {
                return ResourceManager.GetString("lblFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Premium website.
        /// </summary>
        public static string lblfreePremium {
            get {
                return ResourceManager.GetString("lblfreePremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further information.
        /// </summary>
        public static string lblFurtherinfo {
            get {
                return ResourceManager.GetString("lblFurtherinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more profit..
        /// </summary>
        public static string lblGetmorebenefit {
            get {
                return ResourceManager.GetString("lblGetmorebenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Member.
        /// </summary>
        public static string lblGoldMember {
            get {
                return ResourceManager.GetString("lblGoldMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการโฆษณาสินค้าระดับ Gold Member.
        /// </summary>
        public static string lblGoldMember1 {
            get {
                return ResourceManager.GetString("lblGoldMember1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิการใช้บริการแนะนำสินค้า ทำให้ผู้ซื้อมีโอกาสพบสินค้าของคุณในหน้าจอที่มีผู้เข้าชมมากที่สุด.
        /// </summary>
        public static string lblGoldMember2 {
            get {
                return ResourceManager.GetString("lblGoldMember2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิประโยชน์อื่น ๆ เมื่อใช้ Gold Member.
        /// </summary>
        public static string lblGoldMember3 {
            get {
                return ResourceManager.GetString("lblGoldMember3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประกาศรับสมัครงาน ไม่จำกัดจำนวน.
        /// </summary>
        public static string lblGoldMember4 {
            get {
                return ResourceManager.GetString("lblGoldMember4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฟรี โปรแกรมบัญชีสำเร็จรูป.
        /// </summary>
        public static string lblGoldMember5 {
            get {
                return ResourceManager.GetString("lblGoldMember5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฟรี เว็บไซต์สำเร็จรูป Package M.
        /// </summary>
        public static string lblGoldMember6 {
            get {
                return ResourceManager.GetString("lblGoldMember6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลด 70% ที่ วิมานน้ำ รีสอร์ท.
        /// </summary>
        public static string lblGoldMember7 {
            get {
                return ResourceManager.GetString("lblGoldMember7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the Gold member will get.
        /// </summary>
        public static string lblGoldmemberget {
            get {
                return ResourceManager.GetString("lblGoldmemberget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Member.
        /// </summary>
        public static string lblGoldpackage {
            get {
                return ResourceManager.GetString("lblGoldpackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppStoreThai Help and Support.
        /// </summary>
        public static string lblhelpsupport {
            get {
                return ResourceManager.GetString("lblhelpsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Hotline &amp; Matching center.
        /// </summary>
        public static string lblHotlineMatching {
            get {
                return ResourceManager.GetString("lblHotlineMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When any demand for your product comes we are ready to matching the demand with the supply our Gold member to ensure lead information and supporting information to increase sales..
        /// </summary>
        public static string lblHotlineMatchingDesc {
            get {
                return ResourceManager.GetString("lblHotlineMatchingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าค้นหาสินค้า (Hot Product).
        /// </summary>
        public static string lblHotProduct {
            get {
                return ResourceManager.GetString("lblHotProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to add product information.
        /// </summary>
        public static string lblhowtoaddproduct {
            get {
                return ResourceManager.GetString("lblhowtoaddproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to register.
        /// </summary>
        public static string lblhowtoregister {
            get {
                return ResourceManager.GetString("lblhowtoregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important information from B2BThaiExport.com.
        /// </summary>
        public static string lblImportantInfo {
            get {
                return ResourceManager.GetString("lblImportantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We increase the channel to access to your products as much as possible. Like the phrase said “the content is a king”.
        /// </summary>
        public static string lblIncreaseChannel {
            get {
                return ResourceManager.GetString("lblIncreaseChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more online spaces you have and the more products you display. The more chance of your products to find out on Search Engine.
        /// </summary>
        public static string lblIncreaseChannelDesc {
            get {
                return ResourceManager.GetString("lblIncreaseChannelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์งานด่วน นามบัตร
        ///การ์ด สติ๊กเกอร์ ไม่มีขั้นต่ำ
        ///จัดส่งทั่วประเทศ.
        /// </summary>
        public static string lblIsara {
            get {
                return ResourceManager.GetString("lblIsara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job site.
        /// </summary>
        public static string lblJobsite {
            get {
                return ResourceManager.GetString("lblJobsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lately.
        /// </summary>
        public static string lblLately {
            get {
                return ResourceManager.GetString("lblLately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string lblLearnmore {
            get {
                return ResourceManager.GetString("lblLearnmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to other services.
        /// </summary>
        public static string lblLinkotherservices {
            get {
                return ResourceManager.GetString("lblLinkotherservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get special offer from B2BThaiExport.com
        ///To allow such sales easier such as 
        ///purchasing hotline, matching center.
        /// </summary>
        public static string lblLinkotherservicesDesc {
            get {
                return ResourceManager.GetString("lblLinkotherservicesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LionJob.com.
        /// </summary>
        public static string lblLionJob {
            get {
                return ResourceManager.GetString("lblLionJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@AppStoreThai.com.
        /// </summary>
        public static string lblmailsale_ad {
            get {
                return ResourceManager.GetString("lblmailsale_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map of Prosoft Comtech Co., Ltd..
        /// </summary>
        public static string lblmap {
            get {
                return ResourceManager.GetString("lblmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Maximum number of items.
        /// </summary>
        public static string lblMaxProduct {
            get {
                return ResourceManager.GetString("lblMaxProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 1 - Join website.
        /// </summary>
        public static string lblmemberchapter1 {
            get {
                return ResourceManager.GetString("lblmemberchapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 2 - Sign in MyB2B.
        /// </summary>
        public static string lblmemberchapter2 {
            get {
                return ResourceManager.GetString("lblmemberchapter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 3 - Member Profile.
        /// </summary>
        public static string lblmemberchapter3 {
            get {
                return ResourceManager.GetString("lblmemberchapter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 4 - Upgrade Gold Member.
        /// </summary>
        public static string lblmemberchapter4 {
            get {
                return ResourceManager.GetString("lblmemberchapter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member User Guide.
        /// </summary>
        public static string lblMemberGuide {
            get {
                return ResourceManager.GetString("lblMemberGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Help.
        /// </summary>
        public static string lblmemberhelp {
            get {
                return ResourceManager.GetString("lblmemberhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เดือน.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More web page designs.
        /// </summary>
        public static string lblmoredesign {
            get {
                return ResourceManager.GetString("lblmoredesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myAccount.
        /// </summary>
        public static string lblmyAccount {
            get {
                return ResourceManager.GetString("lblmyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting software for SMEs businesses, carefully accounting for all processes, save times, save costs, reduce difficulty processes, and save human resources for all operating.
        /// </summary>
        public static string lblmyAccountDesc {
            get {
                return ResourceManager.GetString("lblmyAccountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new function Product Store.
        /// </summary>
        public static string lblnewfunction {
            get {
                return ResourceManager.GetString("lblnewfunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported to search vendors easier 
        ///Gold member ensure that product information is targeted to your target before other.
        /// </summary>
        public static string lblnewfunctionDesc {
            get {
                return ResourceManager.GetString("lblnewfunctionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string lblNews {
            get {
                return ResourceManager.GetString("lblNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not the problem even you already have a website,.
        /// </summary>
        public static string lblnotwebsite {
            get {
                return ResourceManager.GetString("lblnotwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other way to increase access to customer information Similarly, you have a lot of information on the online world, when you search (search engine) there will be more chance than typical site as twofold.
        /// </summary>
        public static string lblnotwebsiteDesc {
            get {
                return ResourceManager.GetString("lblnotwebsiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string lblNow {
            get {
                return ResourceManager.GetString("lblNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Office Hours : Monday - Friday 8.30 - 18.00 except on Official holidays).
        /// </summary>
        public static string lblofficehouse {
            get {
                return ResourceManager.GetString("lblofficehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online advertisemnet system.
        /// </summary>
        public static string lblOnlineAds {
            get {
                return ResourceManager.GetString("lblOnlineAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otop product.
        /// </summary>
        public static string lblotopproduct {
            get {
                return ResourceManager.GetString("lblotopproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package M.
        /// </summary>
        public static string lblPackage_M {
            get {
                return ResourceManager.GetString("lblPackage_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package PDF form printing.
        /// </summary>
        public static string lblPackagePDF {
            get {
                return ResourceManager.GetString("lblPackagePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string lblPDF {
            get {
                return ResourceManager.GetString("lblPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. (081) 359-7680.
        /// </summary>
        public static string lblPhones {
            get {
                return ResourceManager.GetString("lblPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string lblPolicy {
            get {
                return ResourceManager.GetString("lblPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post for the new employee.
        /// </summary>
        public static string lblPostemployee {
            get {
                return ResourceManager.GetString("lblPostemployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a job on the website.
        /// </summary>
        public static string lblPostJob {
            get {
                return ResourceManager.GetString("lblPostJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link a working function with www.lionjob.com the biggest job seeking website of Thailand, seeking for new employee, seeking any job positions or job offering with easily, quickly and thoroughly.
        /// </summary>
        public static string lblPostJobDesc {
            get {
                return ResourceManager.GetString("lblPostJobDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by Prosoft Group.
        /// </summary>
        public static string lblPowerprosoftgroup {
            get {
                return ResourceManager.GetString("lblPowerprosoftgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้ารายละเอียดสินค้า (Premium Product).
        /// </summary>
        public static string lblPremiumProduct {
            get {
                return ResourceManager.GetString("lblPremiumProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free! Company Website.
        /// </summary>
        public static string lblPremiumWebsite {
            get {
                return ResourceManager.GetString("lblPremiumWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Website theme more than 30 themes which appropriate with your business.
        /// </summary>
        public static string lblPremiumWebsiteDesc {
            get {
                return ResourceManager.GetString("lblPremiumWebsiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string lblPreview {
            get {
                return ResourceManager.GetString("lblPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string lblPrint {
            get {
                return ResourceManager.GetString("lblPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Package information and advertising payment.
        /// </summary>
        public static string lblPrintPackageinfo {
            get {
                return ResourceManager.GetString("lblPrintPackageinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400,000 Product.
        /// </summary>
        public static string lblProductinList {
            get {
                return ResourceManager.GetString("lblProductinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products more easily.
        /// </summary>
        public static string lblProductsEasily {
            get {
                return ResourceManager.GetString("lblProductsEasily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the very first show of search results
        ///Make buyers more likely to fide your product..
        /// </summary>
        public static string lblProductsEasyDesc {
            get {
                return ResourceManager.GetString("lblProductsEasyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรโมชั่นสำหรับ Gold Member.
        /// </summary>
        public static string lblProGold {
            get {
                return ResourceManager.GetString("lblProGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive 1 year free!.
        /// </summary>
        public static string lblProgramfree {
            get {
                return ResourceManager.GetString("lblProgramfree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A gold member on the www.AppStoreThai.com , the privileged more than worth! Get 1 year free!.
        /// </summary>
        public static string lblProgramfreeDesc {
            get {
                return ResourceManager.GetString("lblProgramfreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to promote unlimited products.
        /// </summary>
        public static string lblPromoteProduct {
            get {
                return ResourceManager.GetString("lblPromoteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main product category 29 categories would identify target market and online sale is unlimited with the low cost.
        /// </summary>
        public static string lblPromoteProductDesc {
            get {
                return ResourceManager.GetString("lblPromoteProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string lblPromotion {
            get {
                return ResourceManager.GetString("lblPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Center.
        /// </summary>
        public static string lblPurchasesquare {
            get {
                return ResourceManager.GetString("lblPurchasesquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make trade easy and more convenient.
        /// </summary>
        public static string lblPurchasesquareDesc {
            get {
                return ResourceManager.GetString("lblPurchasesquareDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending invoice and receipt from AppStoreThai.
        /// </summary>
        public static string lblreceipt {
            get {
                return ResourceManager.GetString("lblreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for sign in to B2BMyanmar.com &amp; can use account for other services as follows :.
        /// </summary>
        public static string lblregisterfor {
            get {
                return ResourceManager.GetString("lblregisterfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantee reliable with your customer.
        /// </summary>
        public static string lblReliableCustomer {
            get {
                return ResourceManager.GetString("lblReliableCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create online web page like a premium website as your online product showroom and also display your company profiles..
        /// </summary>
        public static string lblReliableCustomerDesc {
            get {
                return ResourceManager.GetString("lblReliableCustomerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblRemakeUp {
            get {
                return ResourceManager.GetString("lblRemakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment does not include bank transfer fees. If there is any fee, the company reserves the right to charge the customer is responsible..
        /// </summary>
        public static string lblRemarkDesc {
            get {
                return ResourceManager.GetString("lblRemarkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblRemarkDescs {
            get {
                return ResourceManager.GetString("lblRemarkDescs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can request to advertise at.
        /// </summary>
        public static string lblrequestadstel {
            get {
                return ResourceManager.GetString("lblrequestadstel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2C shopping.
        /// </summary>
        public static string lblsecondhandshopping {
            get {
                return ResourceManager.GetString("lblsecondhandshopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 1 - Post Product.
        /// </summary>
        public static string lblsellchapter1 {
            get {
                return ResourceManager.GetString("lblsellchapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 2 - Manage Product.
        /// </summary>
        public static string lblsellchapter2 {
            get {
                return ResourceManager.GetString("lblsellchapter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 3 - Manage Recommend Product.
        /// </summary>
        public static string lblsellchapter3 {
            get {
                return ResourceManager.GetString("lblsellchapter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 4 - Contact to Buyer.
        /// </summary>
        public static string lblsellchapter4 {
            get {
                return ResourceManager.GetString("lblsellchapter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 5 - Bid Price.
        /// </summary>
        public static string lblsellchapter5 {
            get {
                return ResourceManager.GetString("lblsellchapter5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,000 sellers.
        /// </summary>
        public static string lblSellersinList {
            get {
                return ResourceManager.GetString("lblSellersinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าบริการ.
        /// </summary>
        public static string lblServiceCharge {
            get {
                return ResourceManager.GetString("lblServiceCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping document.
        /// </summary>
        public static string lblshippingdoc {
            get {
                return ResourceManager.GetString("lblshippingdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string lblSitemap {
            get {
                return ResourceManager.GetString("lblSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support B2BThai.
        /// </summary>
        public static string lblskype {
            get {
                return ResourceManager.GetString("lblskype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software program trading.
        /// </summary>
        public static string lblsoftwaretrading {
            get {
                return ResourceManager.GetString("lblsoftwaretrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.SoGoodWeb.com.
        /// </summary>
        public static string lblSoGood {
            get {
                return ResourceManager.GetString("lblSoGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บางส่วน.
        /// </summary>
        public static string lblsome {
            get {
                return ResourceManager.GetString("lblsome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sort of product display/declaration purchase.
        /// </summary>
        public static string lblSortproductDisplay {
            get {
                return ResourceManager.GetString("lblSortproductDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Promotion.
        /// </summary>
        public static string lblspecialpromotion {
            get {
                return ResourceManager.GetString("lblspecialpromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you buy 1 year gold package immediately get 50% discount from 24,000 baht to 12,000 baht/year.
        /// </summary>
        public static string lblspecialpromotionDesc {
            get {
                return ResourceManager.GetString("lblspecialpromotionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string lblSuggestion {
            get {
                return ResourceManager.GetString("lblSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier User Guide.
        /// </summary>
        public static string lblSupplierGuide {
            get {
                return ResourceManager.GetString("lblSupplierGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Help.
        /// </summary>
        public static string lblsupplierhelp {
            get {
                return ResourceManager.GetString("lblsupplierhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppStoreThai  Survey new feature..
        /// </summary>
        public static string lblSurveyfeature {
            get {
                return ResourceManager.GetString("lblSurveyfeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold package.
        /// </summary>
        public static string lblTabGoldpackage {
            get {
                return ResourceManager.GetString("lblTabGoldpackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Advertise.
        /// </summary>
        public static string lblTabhowtoAds {
            get {
                return ResourceManager.GetString("lblTabhowtoAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to make a payment.
        /// </summary>
        public static string lblTabhowtoPayment {
            get {
                return ResourceManager.GetString("lblTabhowtoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Withholding tax can be deducted as a cost of 2% of the total amount exclude VAT 7%.
        /// </summary>
        public static string lbltaxdeduct {
            get {
                return ResourceManager.GetString("lbltaxdeduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * All transfer prices must be included VAT 7% and any transfer fee!.
        /// </summary>
        public static string lbltaxinclude {
            get {
                return ResourceManager.GetString("lbltaxinclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02-402-8413.
        /// </summary>
        public static string lbltelCustomer_Service {
            get {
                return ResourceManager.GetString("lbltelCustomer_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02-402-8413.
        /// </summary>
        public static string lbltelnumber {
            get {
                return ResourceManager.GetString("lbltelnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02-402-8413.
        /// </summary>
        public static string lbltelsale_ad {
            get {
                return ResourceManager.GetString("lbltelsale_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string lblTemplate {
            get {
                return ResourceManager.GetString("lblTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of Use.
        /// </summary>
        public static string lbltermofuse {
            get {
                return ResourceManager.GetString("lbltermofuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เว็บไซต์ที่เป็นตัวกลางในการติดต่อซื้อ-ขายสินค้าธุรกิจของคุณ ทำให้การดำเนินธุรกิจซื้อ-ขายของคุณเป็นเรื่องง่าย.
        /// </summary>
        public static string lbltext1 {
            get {
                return ResourceManager.GetString("lbltext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ด้วยระบบบริการที่มีมากมายกว่า 20 ระบบ สินค้าที่มากถึง 300,000 รายการ และผู้ขายในระบบมากกว่า 6,000 ราย.
        /// </summary>
        public static string lbltext2 {
            get {
                return ResourceManager.GetString("lbltext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product catalog will be top on catalog page.
        /// </summary>
        public static string lbltopcatalog {
            get {
                return ResourceManager.GetString("lbltopcatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top list techniques.
        /// </summary>
        public static string lbltoplisttechnic {
            get {
                return ResourceManager.GetString("lbltoplisttechnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to bank account.
        /// </summary>
        public static string lbltransferbank {
            get {
                return ResourceManager.GetString("lbltransferbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Access to Leads’ information (buys-sells).
        /// </summary>
        public static string lblunlimetedAccessDesc1 {
            get {
                return ResourceManager.GetString("lblunlimetedAccessDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Receive a news, an exclusive, and any discounted before anyone else.
        /// </summary>
        public static string lblunlimetedAccessDesc2 {
            get {
                return ResourceManager.GetString("lblunlimetedAccessDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        public static string lblUnlimited {
            get {
                return ResourceManager.GetString("lblUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold member is unlimited to access any information.
        /// </summary>
        public static string lblUnlimitedAccess {
            get {
                return ResourceManager.GetString("lblUnlimitedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Gold.
        /// </summary>
        public static string lblUpgradeGold {
            get {
                return ResourceManager.GetString("lblUpgradeGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลดที่พัก 70%.
        /// </summary>
        public static string lblValue {
            get {
                return ResourceManager.GetString("lblValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can log in website (www.AppStoreThai.com).
        /// </summary>
        public static string lblviadesc1 {
            get {
                return ResourceManager.GetString("lblviadesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in order to add, delete, or edit product information.
        /// </summary>
        public static string lblviadesc2 {
            get {
                return ResourceManager.GetString("lblviadesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that you want to advertise all the time or Email to sale@AppStoreThai.com.
        /// </summary>
        public static string lblviadesc3 {
            get {
                return ResourceManager.GetString("lblviadesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via internet &amp; website.
        /// </summary>
        public static string lblviainternetwebsite {
            get {
                return ResourceManager.GetString("lblviainternetwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วิมานน้ำ รีสอร์ท.
        /// </summary>
        public static string lblVimanNom {
            get {
                return ResourceManager.GetString("lblVimanNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us ,Vision, Mission.
        /// </summary>
        public static string lblvisionmission {
            get {
                return ResourceManager.GetString("lblvisionmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,000 visitors/day.
        /// </summary>
        public static string lblVisitorinList {
            get {
                return ResourceManager.GetString("lblVisitorinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 1 - Company Website.
        /// </summary>
        public static string lblwebsitechapter1 {
            get {
                return ResourceManager.GetString("lblwebsitechapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 2 - Website Template.
        /// </summary>
        public static string lblwebsitechapter2 {
            get {
                return ResourceManager.GetString("lblwebsitechapter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter 3 - Recommend Product.
        /// </summary>
        public static string lblwebsitechapter3 {
            get {
                return ResourceManager.GetString("lblwebsitechapter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Website.
        /// </summary>
        public static string lblwebsitehelp {
            get {
                return ResourceManager.GetString("lblwebsitehelp", resourceCulture);
            }
        }
    }
}
