//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buylead {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buylead() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Buylead", typeof(Buylead).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lbladsrateaddr3 {
            get {
                return ResourceManager.GetString("lbladsrateaddr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Buylead.
        /// </summary>
        public static string lblApproveBuylead {
            get {
                return ResourceManager.GetString("lblApproveBuylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying Request.
        /// </summary>
        public static string lblBuyerData {
            get {
                return ResourceManager.GetString("lblBuyerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buylead.
        /// </summary>
        public static string lblBuylead {
            get {
                return ResourceManager.GetString("lblBuylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมวดหมู่ประกาศซื้อ.
        /// </summary>
        public static string lblBuyleadCate {
            get {
                return ResourceManager.GetString("lblBuyleadCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying Request Code.
        /// </summary>
        public static string lblBuyleadCode {
            get {
                return ResourceManager.GetString("lblBuyleadCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string lblBuyleadCreate {
            get {
                return ResourceManager.GetString("lblBuyleadCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Request.
        /// </summary>
        public static string lblBuyleadData {
            get {
                return ResourceManager.GetString("lblBuyleadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buylead Details.
        /// </summary>
        public static string lblBuyleadDetail {
            get {
                return ResourceManager.GetString("lblBuyleadDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date.
        /// </summary>
        public static string lblBuyleadExpDate {
            get {
                return ResourceManager.GetString("lblBuyleadExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date.
        /// </summary>
        public static string lblBuyleadExpire {
            get {
                return ResourceManager.GetString("lblBuyleadExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Buying Request.
        /// </summary>
        public static string lblBuyleadExpired {
            get {
                return ResourceManager.GetString("lblBuyleadExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปสินค้าที่ต้องการ.
        /// </summary>
        public static string lblBuyleadImage {
            get {
                return ResourceManager.GetString("lblBuyleadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Buying Request, tell the supplier What you want.
        /// </summary>
        public static string lblBuyleadLabel {
            get {
                return ResourceManager.GetString("lblBuyleadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please put your contact, supplier will contact you.
        /// </summary>
        public static string lblBuyleadLabel2 {
            get {
                return ResourceManager.GetString("lblBuyleadLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying request Name.
        /// </summary>
        public static string lblBuyleadName {
            get {
                return ResourceManager.GetString("lblBuyleadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string lblBuyleadSetDefalut {
            get {
                return ResourceManager.GetString("lblBuyleadSetDefalut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying request type.
        /// </summary>
        public static string lblBuyleadtype {
            get {
                return ResourceManager.GetString("lblBuyleadtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated order quantity.
        /// </summary>
        public static string lblBuyleadUnit {
            get {
                return ResourceManager.GetString("lblBuyleadUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string lblChannel {
            get {
                return ResourceManager.GetString("lblChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลติดต่อผู้ประกาศซื้อ.
        /// </summary>
        public static string lblCompContactBuylead {
            get {
                return ResourceManager.GetString("lblCompContactBuylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string lblContactName {
            get {
                return ResourceManager.GetString("lblContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Quantity.
        /// </summary>
        public static string lblCountBuylead {
            get {
                return ResourceManager.GetString("lblCountBuylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblfaxDesc4 {
            get {
                return ResourceManager.GetString("lblfaxDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblfaxDesc5 {
            get {
                return ResourceManager.GetString("lblfaxDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in a simple form.
        /// </summary>
        public static string lblFill_simple_form {
            get {
                return ResourceManager.GetString("lblFill_simple_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day/month/year.
        /// </summary>
        public static string lblFormatDate {
            get {
                return ResourceManager.GetString("lblFormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline Purchasing.
        /// </summary>
        public static string lblHotline {
            get {
                return ResourceManager.GetString("lblHotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasted Buying Request.
        /// </summary>
        public static string lblLastedBuylead {
            get {
                return ResourceManager.GetString("lblLastedBuylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-Term.
        /// </summary>
        public static string lblLongTermProduct {
            get {
                return ResourceManager.GetString("lblLongTermProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Specific  Buying Code.
        /// </summary>
        public static string lblNoBuyleadCode {
            get {
                return ResourceManager.GetString("lblNoBuyleadCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No View Count.
        /// </summary>
        public static string lblNoViewCount {
            get {
                return ResourceManager.GetString("lblNoViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string lblPositionName {
            get {
                return ResourceManager.GetString("lblPositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุเพิ่มเติม.
        /// </summary>
        public static string lblRemakeUp {
            get {
                return ResourceManager.GetString("lblRemakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report requirements to supplier..
        /// </summary>
        public static string lblReport_req_to_supplier {
            get {
                return ResourceManager.GetString("lblReport_req_to_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-Term.
        /// </summary>
        public static string lblShortTermProduct {
            get {
                return ResourceManager.GetString("lblShortTermProduct", resourceCulture);
            }
        }
    }
}
