//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Cart", typeof(Cart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number,Village No.
        /// </summary>
        public static string lblAddress1Buyer {
            get {
                return ResourceManager.GetString("lblAddress1Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alley,Road.
        /// </summary>
        public static string lblAddress2Buyer {
            get {
                return ResourceManager.GetString("lblAddress2Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string lblAddressend {
            get {
                return ResourceManager.GetString("lblAddressend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string lblDistrict {
            get {
                return ResourceManager.GetString("lblDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblemailbuyer {
            get {
                return ResourceManager.GetString("lblemailbuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblnamebuyer {
            get {
                return ResourceManager.GetString("lblnamebuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal.
        /// </summary>
        public static string lblPostal {
            get {
                return ResourceManager.GetString("lblPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string lblProvice {
            get {
                return ResourceManager.GetString("lblProvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sername.
        /// </summary>
        public static string lblsernamebuyer {
            get {
                return ResourceManager.GetString("lblsernamebuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubDistrict.
        /// </summary>
        public static string lblSubDistrict {
            get {
                return ResourceManager.GetString("lblSubDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Amount.
        /// </summary>
        public static string lbltable_amountorder {
            get {
                return ResourceManager.GetString("lbltable_amountorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Product.
        /// </summary>
        public static string lbltable_detail {
            get {
                return ResourceManager.GetString("lbltable_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lbltable_price {
            get {
                return ResourceManager.GetString("lbltable_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Price.
        /// </summary>
        public static string lbltable_shipping {
            get {
                return ResourceManager.GetString("lbltable_shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string lbltable_totalprice {
            get {
                return ResourceManager.GetString("lbltable_totalprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string lbltelbuyer {
            get {
                return ResourceManager.GetString("lbltelbuyer", resourceCulture);
            }
        }
    }
}
