//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Company {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Company() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Company", typeof(Company).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message.
        /// </summary>
        public static string btnSendMessage {
            get {
                return ResourceManager.GetString("btnSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string lblAccount {
            get {
                return ResourceManager.GetString("lblAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Setting.
        /// </summary>
        public static string lblAccount_Setting {
            get {
                return ResourceManager.GetString("lblAccount_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Account.
        /// </summary>
        public static string lblAccountData {
            get {
                return ResourceManager.GetString("lblAccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string lblArticle {
            get {
                return ResourceManager.GetString("lblArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        public static string lblBizType {
            get {
                return ResourceManager.GetString("lblBizType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string lblBlog {
            get {
                return ResourceManager.GetString("lblBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Subject.
        /// </summary>
        public static string lblBlog_Name {
            get {
                return ResourceManager.GetString("lblBlog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Businesses Type.
        /// </summary>
        public static string lblBusinesses {
            get {
                return ResourceManager.GetString("lblBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certify Name.
        /// </summary>
        public static string lblCertify_name {
            get {
                return ResourceManager.GetString("lblCertify_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request .
        /// </summary>
        public static string lblChange_Request {
            get {
                return ResourceManager.GetString("lblChange_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercial Number.
        /// </summary>
        public static string lblComercial_no {
            get {
                return ResourceManager.GetString("lblComercial_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Business Template.
        /// </summary>
        public static string lblCommonTemplate {
            get {
                return ResourceManager.GetString("lblCommonTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Code.
        /// </summary>
        public static string lblComp_code {
            get {
                return ResourceManager.GetString("lblComp_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Profile.
        /// </summary>
        public static string lblComp_Detail {
            get {
                return ResourceManager.GetString("lblComp_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Map.
        /// </summary>
        public static string lblComp_Map {
            get {
                return ResourceManager.GetString("lblComp_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Setting.
        /// </summary>
        public static string lblComp_setting {
            get {
                return ResourceManager.GetString("lblComp_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration.
        /// </summary>
        public static string lblCompany_Profile {
            get {
                return ResourceManager.GetString("lblCompany_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Map.
        /// </summary>
        public static string lblCompanyMap {
            get {
                return ResourceManager.GetString("lblCompanyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification.
        /// </summary>
        public static string lblCompCertify {
            get {
                return ResourceManager.GetString("lblCompCertify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates and Award.
        /// </summary>
        public static string lblCompCertifyandAward {
            get {
                return ResourceManager.GetString("lblCompCertifyandAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Contact.
        /// </summary>
        public static string lblCompContact {
            get {
                return ResourceManager.GetString("lblCompContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company History.
        /// </summary>
        public static string lblCompHistory {
            get {
                return ResourceManager.GetString("lblCompHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Picture.
        /// </summary>
        public static string lblCompImg {
            get {
                return ResourceManager.GetString("lblCompImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo.
        /// </summary>
        public static string lblCompLogo {
            get {
                return ResourceManager.GetString("lblCompLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string lblCompName {
            get {
                return ResourceManager.GetString("lblCompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Payment Term.
        /// </summary>
        public static string lblCompPayment {
            get {
                return ResourceManager.GetString("lblCompPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Picture.
        /// </summary>
        public static string lblCompPic {
            get {
                return ResourceManager.GetString("lblCompPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Production.
        /// </summary>
        public static string lblCompProduction {
            get {
                return ResourceManager.GetString("lblCompProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Shipment.
        /// </summary>
        public static string lblCompShipment {
            get {
                return ResourceManager.GetString("lblCompShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Template.
        /// </summary>
        public static string lblCompWebsite {
            get {
                return ResourceManager.GetString("lblCompWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        public static string lblContactDetail {
            get {
                return ResourceManager.GetString("lblContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number.
        /// </summary>
        public static string lblContactNumber {
            get {
                return ResourceManager.GetString("lblContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Image.
        /// </summary>
        public static string lblContImg {
            get {
                return ResourceManager.GetString("lblContImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management companies to display your Company Website..
        /// </summary>
        public static string lblDisplaycompweb {
            get {
                return ResourceManager.GetString("lblDisplaycompweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Expire Date.
        /// </summary>
        public static string lblEdit_expiredate {
            get {
                return ResourceManager.GetString("lblEdit_expiredate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of QC Staff.
        /// </summary>
        public static string lblEm_QC {
            get {
                return ResourceManager.GetString("lblEm_QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of R &amp; D Staff.
        /// </summary>
        public static string lblEmp_R_and_D {
            get {
                return ResourceManager.GetString("lblEmp_R_and_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        public static string lblEstimate {
            get {
                return ResourceManager.GetString("lblEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory&apos;s Address.
        /// </summary>
        public static string lblFact_addr {
            get {
                return ResourceManager.GetString("lblFact_addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory&apos;s Size.
        /// </summary>
        public static string lblFact_size {
            get {
                return ResourceManager.GetString("lblFact_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder.
        /// </summary>
        public static string lblFounder {
            get {
                return ResourceManager.GetString("lblFounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder and owned company.
        /// </summary>
        public static string lblFounder_Owner {
            get {
                return ResourceManager.GetString("lblFounder_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Business Template.
        /// </summary>
        public static string lblGoldTemplate {
            get {
                return ResourceManager.GetString("lblGoldTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map.
        /// </summary>
        public static string lblGoogleMap {
            get {
                return ResourceManager.GetString("lblGoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Overview.
        /// </summary>
        public static string lblGuide {
            get {
                return ResourceManager.GetString("lblGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance.
        /// </summary>
        public static string lblImportance {
            get {
                return ResourceManager.GetString("lblImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Industry.
        /// </summary>
        public static string lblIndustries {
            get {
                return ResourceManager.GetString("lblIndustries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string lblJob {
            get {
                return ResourceManager.GetString("lblJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest supplier.
        /// </summary>
        public static string lblLast_supplier {
            get {
                return ResourceManager.GetString("lblLast_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Product.
        /// </summary>
        public static string lblMainProduct {
            get {
                return ResourceManager.GetString("lblMainProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Site.
        /// </summary>
        public static string lblMajorMarket {
            get {
                return ResourceManager.GetString("lblMajorMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Description.
        /// </summary>
        public static string lblMap_Detail {
            get {
                return ResourceManager.GetString("lblMap_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapLongtitude.
        /// </summary>
        public static string lblMapLongtitude {
            get {
                return ResourceManager.GetString("lblMapLongtitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Site.
        /// </summary>
        public static string lblMarketGroup {
            get {
                return ResourceManager.GetString("lblMarketGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Center.
        /// </summary>
        public static string lblMessage_Center {
            get {
                return ResourceManager.GetString("lblMessage_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Site.
        /// </summary>
        public static string lblMinorMarket {
            get {
                return ResourceManager.GetString("lblMinorMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        public static string lblMobilePhone {
            get {
                return ResourceManager.GetString("lblMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More….
        /// </summary>
        public static string lblMore {
            get {
                return ResourceManager.GetString("lblMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyB2B Update.
        /// </summary>
        public static string lblMyWebsite_Upd {
            get {
                return ResourceManager.GetString("lblMyWebsite_Upd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string lblNew_Request {
            get {
                return ResourceManager.GetString("lblNew_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblNotFound2 {
            get {
                return ResourceManager.GetString("lblNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employer.
        /// </summary>
        public static string lblNum_Emp {
            get {
                return ResourceManager.GetString("lblNum_Emp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order&amp;Payment.
        /// </summary>
        public static string lblOrder_Payment {
            get {
                return ResourceManager.GetString("lblOrder_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of order.
        /// </summary>
        public static string lblOrderList {
            get {
                return ResourceManager.GetString("lblOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Order.
        /// </summary>
        public static string lblOrderPackage {
            get {
                return ResourceManager.GetString("lblOrderPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Business Type.
        /// </summary>
        public static string lblOtherBizType {
            get {
                return ResourceManager.GetString("lblOtherBizType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string lblOwner {
            get {
                return ResourceManager.GetString("lblOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string lblOwner2 {
            get {
                return ResourceManager.GetString("lblOwner2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string lblPackage {
            get {
                return ResourceManager.GetString("lblPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Payment.
        /// </summary>
        public static string lblPaymentList {
            get {
                return ResourceManager.GetString("lblPaymentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string lblPeople {
            get {
                return ResourceManager.GetString("lblPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinLatitude.
        /// </summary>
        public static string lblPinLatitude {
            get {
                return ResourceManager.GetString("lblPinLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinLongtitude.
        /// </summary>
        public static string lblPinLongtitude {
            get {
                return ResourceManager.GetString("lblPinLongtitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Now.
        /// </summary>
        public static string lblPost_Now {
            get {
                return ResourceManager.GetString("lblPost_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview company website.
        /// </summary>
        public static string lblPreview_Comp {
            get {
                return ResourceManager.GetString("lblPreview_Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Register Address.
        /// </summary>
        public static string lblPro_addr {
            get {
                return ResourceManager.GetString("lblPro_addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Price.
        /// </summary>
        public static string lblQuotation {
            get {
                return ResourceManager.GetString("lblQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Price.
        /// </summary>
        public static string lblQuotation_Estimate {
            get {
                return ResourceManager.GetString("lblQuotation_Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string lblRead {
            get {
                return ResourceManager.GetString("lblRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Buylead.
        /// </summary>
        public static string lblRecent_Buylead {
            get {
                return ResourceManager.GetString("lblRecent_Buylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Product.
        /// </summary>
        public static string lblRecent_Product {
            get {
                return ResourceManager.GetString("lblRecent_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string lblRegisDate {
            get {
                return ResourceManager.GetString("lblRegisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject .
        /// </summary>
        public static string lblReject {
            get {
                return ResourceManager.GetString("lblReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Report.
        /// </summary>
        public static string lblReportContact {
            get {
                return ResourceManager.GetString("lblReportContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string lblSetting {
            get {
                return ResourceManager.GetString("lblSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        public static string lblShipping {
            get {
                return ResourceManager.GetString("lblShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment  Detail.
        /// </summary>
        public static string lblShipping_Detail {
            get {
                return ResourceManager.GetString("lblShipping_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Inform.
        /// </summary>
        public static string lblSubmitPayment {
            get {
                return ResourceManager.GetString("lblSubmitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel No..
        /// </summary>
        public static string lblTel_No {
            get {
                return ResourceManager.GetString("lblTel_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Buying Request.
        /// </summary>
        public static string lblTotal_Buylead {
            get {
                return ResourceManager.GetString("lblTotal_Buylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Product.
        /// </summary>
        public static string lblTotal_Product {
            get {
                return ResourceManager.GetString("lblTotal_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnRead.
        /// </summary>
        public static string lblUnRead {
            get {
                return ResourceManager.GetString("lblUnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string lblUpgrade {
            get {
                return ResourceManager.GetString("lblUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to a maximum of 3 pictures.
        /// </summary>
        public static string lblUpload_CompImg1 {
            get {
                return ResourceManager.GetString("lblUpload_CompImg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a beautiful display. Pictures should be of equal size.
        /// </summary>
        public static string lblUpload_CompImg2 {
            get {
                return ResourceManager.GetString("lblUpload_CompImg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No larger than 320 x 215  pixel.
        /// </summary>
        public static string lblUpload_CompImg3 {
            get {
                return ResourceManager.GetString("lblUpload_CompImg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format file .jpg .jpeg .gif .png.
        /// </summary>
        public static string lblUpload_CompImg4 {
            get {
                return ResourceManager.GetString("lblUpload_CompImg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No larger than 75 x 75 pixel.
        /// </summary>
        public static string lblUpload_Cont3 {
            get {
                return ResourceManager.GetString("lblUpload_Cont3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose just one picture only.
        /// </summary>
        public static string lblUpload_Logo1 {
            get {
                return ResourceManager.GetString("lblUpload_Logo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a beautiful display.  Images should be square.
        /// </summary>
        public static string lblUpload_Logo2 {
            get {
                return ResourceManager.GetString("lblUpload_Logo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No larger than 100 x 75 pixel.
        /// </summary>
        public static string lblUpload_Logo3 {
            get {
                return ResourceManager.GetString("lblUpload_Logo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format file .jpg .jpeg .gif .png.
        /// </summary>
        public static string lblUpload_Logo4 {
            get {
                return ResourceManager.GetString("lblUpload_Logo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a beautiful display.  Images should be a rectangle.
        /// </summary>
        public static string lblUpload_Map2 {
            get {
                return ResourceManager.GetString("lblUpload_Map2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No larger than 500 x 400 pixel.
        /// </summary>
        public static string lblUpload_Map3 {
            get {
                return ResourceManager.GetString("lblUpload_Map3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Company Information.
        /// </summary>
        public static string lblUserComp {
            get {
                return ResourceManager.GetString("lblUserComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Member Data.
        /// </summary>
        public static string lblUserMem {
            get {
                return ResourceManager.GetString("lblUserMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string lblVisits {
            get {
                return ResourceManager.GetString("lblVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Website.
        /// </summary>
        public static string lblWebSite {
            get {
                return ResourceManager.GetString("lblWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Established.
        /// </summary>
        public static string lblYear_Est {
            get {
                return ResourceManager.GetString("lblYear_Est", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name company.
        /// </summary>
        public static string lblYourCompany {
            get {
                return ResourceManager.GetString("lblYourCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string lblZoom {
            get {
                return ResourceManager.GetString("lblZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapLatitude.
        /// </summary>
        public static string MapLatitude {
            get {
                return ResourceManager.GetString("MapLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Company Website.
        /// </summary>
        public static string titlePreview_Comp {
            get {
                return ResourceManager.GetString("titlePreview_Comp", resourceCulture);
            }
        }
    }
}
