//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B6Aj1kj8nAw=.
        /// </summary>
        public static string BackEnd {
            get {
                return ResourceManager.GetString("BackEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB_B2BServiceColne.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string DefaultPageSize {
            get {
                return ResourceManager.GetString("DefaultPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoalert@ouikum.com.
        /// </summary>
        public static string EmailAlert {
            get {
                return ResourceManager.GetString("EmailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoreply@ouikum.com.
        /// </summary>
        public static string EmailNoReply {
            get {
                return ResourceManager.GetString("EmailNoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.ouikum.com.
        /// </summary>
        public static string EmailServer {
            get {
                return ResourceManager.GetString("EmailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@ouikum.com.
        /// </summary>
        public static string EmailSupport {
            get {
                return ResourceManager.GetString("EmailSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 288277461227399.
        /// </summary>
        public static string Facebook_API_Key {
            get {
                return ResourceManager.GetString("Facebook_API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af9584383f46a9a3a18e0678794068c.
        /// </summary>
        public static string Facebook_API_Secret {
            get {
                return ResourceManager.GetString("Facebook_API_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th-TH.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1qw23er45t@.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.ouikum.com.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string SMTP_IsAuthentication {
            get {
                return ResourceManager.GetString("SMTP_IsAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin@2533.
        /// </summary>
        public static string SMTP_Password {
            get {
                return ResourceManager.GetString("SMTP_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.ouikum.com.
        /// </summary>
        public static string SMTP_Server {
            get {
                return ResourceManager.GetString("SMTP_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@ouikum.com.
        /// </summary>
        public static string SMTP_UserName {
            get {
                return ResourceManager.GetString("SMTP_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string WebID {
            get {
                return ResourceManager.GetString("WebID", resourceCulture);
            }
        }
    }
}
