//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmaiOrderToBuyer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmaiOrderToBuyer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.EmaiOrderToBuyer", typeof(EmaiOrderToBuyer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information and shipping address.
        /// </summary>
        public static string lblAddresssend {
            get {
                return ResourceManager.GetString("lblAddresssend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string lblBuyerAddr {
            get {
                return ResourceManager.GetString("lblBuyerAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblBuyerEmail {
            get {
                return ResourceManager.GetString("lblBuyerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and surname.
        /// </summary>
        public static string lblBuyername {
            get {
                return ResourceManager.GetString("lblBuyername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblBuyertel {
            get {
                return ResourceManager.GetString("lblBuyertel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string lblIndex {
            get {
                return ResourceManager.GetString("lblIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string lblOrderDate {
            get {
                return ResourceManager.GetString("lblOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string lblproduct {
            get {
                return ResourceManager.GetString("lblproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string lblQty {
            get {
                return ResourceManager.GetString("lblQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty/Price.
        /// </summary>
        public static string lblQtyPrice {
            get {
                return ResourceManager.GetString("lblQtyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An order has been sent..
        /// </summary>
        public static string lblresulttobuyer {
            get {
                return ResourceManager.GetString("lblresulttobuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending email Please notify the system administrator..
        /// </summary>
        public static string lblresulttobuyerfalse {
            get {
                return ResourceManager.GetString("lblresulttobuyerfalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to notify the seller of the order..
        /// </summary>
        public static string lblresulttoseller {
            get {
                return ResourceManager.GetString("lblresulttoseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Cost.
        /// </summary>
        public static string lblShipmentPrice {
            get {
                return ResourceManager.GetString("lblShipmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders from.
        /// </summary>
        public static string lblSubjectOrdertoBuyer {
            get {
                return ResourceManager.GetString("lblSubjectOrdertoBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
    }
}
