//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.JS", typeof(JS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add buylead success..
        /// </summary>
        public static string vldadd_buylead_success {
            get {
                return ResourceManager.GetString("vldadd_buylead_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to your favorites..
        /// </summary>
        public static string vldadd_fav {
            get {
                return ResourceManager.GetString("vldadd_fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add favorite success all.
        /// </summary>
        public static string vldadd_fav_all {
            get {
                return ResourceManager.GetString("vldadd_fav_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more details..
        /// </summary>
        public static string vldadd_moredetail {
            get {
                return ResourceManager.GetString("vldadd_moredetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add has successfully..
        /// </summary>
        public static string vldadd_succss {
            get {
                return ResourceManager.GetString("vldadd_succss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Agreement.
        /// </summary>
        public static string vldAgreement {
            get {
                return ResourceManager.GetString("vldAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have messages.
        /// </summary>
        public static string vldalert_message {
            get {
                return ResourceManager.GetString("vldalert_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Category.
        /// </summary>
        public static string vldall_cate {
            get {
                return ResourceManager.GetString("vldall_cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items listed to favorite.
        /// </summary>
        public static string vldall_fav_success {
            get {
                return ResourceManager.GetString("vldall_fav_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        public static string vldall_required {
            get {
                return ResourceManager.GetString("vldall_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Provinces.
        /// </summary>
        public static string vldAllProvinces {
            get {
                return ResourceManager.GetString("vldAllProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your source bank..
        /// </summary>
        public static string vldbankid {
            get {
                return ResourceManager.GetString("vldbankid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the fields that have been paid..
        /// </summary>
        public static string vldbranchname {
            get {
                return ResourceManager.GetString("vldbranchname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buylead expire date incorrect..
        /// </summary>
        public static string vldbuyleadexpire {
            get {
                return ResourceManager.GetString("vldbuyleadexpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be saved..
        /// </summary>
        public static string vldcan_save {
            get {
                return ResourceManager.GetString("vldcan_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string vldcancel {
            get {
                return ResourceManager.GetString("vldcancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot check information, Please try again..
        /// </summary>
        public static string vldcannot_check_info {
            get {
                return ResourceManager.GetString("vldcannot_check_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not close the bid..
        /// </summary>
        public static string vldcannot_closebid {
            get {
                return ResourceManager.GetString("vldcannot_closebid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not insert less than 0..
        /// </summary>
        public static string vldcannot_insert_zero {
            get {
                return ResourceManager.GetString("vldcannot_insert_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be saved..
        /// </summary>
        public static string vldcannot_save {
            get {
                return ResourceManager.GetString("vldcannot_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string vldcategory {
            get {
                return ResourceManager.GetString("vldcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password successfully..
        /// </summary>
        public static string vldchange_pass_success {
            get {
                return ResourceManager.GetString("vldchange_pass_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password error. Please try again later..
        /// </summary>
        public static string vldchange_password_error {
            get {
                return ResourceManager.GetString("vldchange_password_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your close the product and then bid. Other supplier will not be able to bid wait product that you have been able to contact you via your email..
        /// </summary>
        public static string vldclosebidproduct {
            get {
                return ResourceManager.GetString("vldclosebidproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose product to compare..
        /// </summary>
        public static string vldcompare_choose {
            get {
                return ResourceManager.GetString("vldcompare_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has exist compare product..
        /// </summary>
        public static string vldcompare_exist {
            get {
                return ResourceManager.GetString("vldcompare_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare products has full..
        /// </summary>
        public static string vldcompare_max {
            get {
                return ResourceManager.GetString("vldcompare_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd compare success..
        /// </summary>
        public static string vldcompare_success {
            get {
                return ResourceManager.GetString("vldcompare_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is duplicate..
        /// </summary>
        public static string vldcompname_exists {
            get {
                return ResourceManager.GetString("vldcompname_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string vldconfirm {
            get {
                return ResourceManager.GetString("vldconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete this item..
        /// </summary>
        public static string vldconfirm_del {
            get {
                return ResourceManager.GetString("vldconfirm_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete all item..
        /// </summary>
        public static string vldconfirm_del_all {
            get {
                return ResourceManager.GetString("vldconfirm_del_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you want to delete category?.
        /// </summary>
        public static string vldconfirm_del_cate {
            get {
                return ResourceManager.GetString("vldconfirm_del_cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you want to delete data?.
        /// </summary>
        public static string vldconfirm_del_data {
            get {
                return ResourceManager.GetString("vldconfirm_del_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you want to delete members ?.
        /// </summary>
        public static string vldconfirm_del_mem {
            get {
                return ResourceManager.GetString("vldconfirm_del_mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you want to delete packet?.
        /// </summary>
        public static string vldconfirm_del_packet {
            get {
                return ResourceManager.GetString("vldconfirm_del_packet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อความแจ้ง Gold Member Package หมดอายุแล้ว.
        /// </summary>
        public static string vldconfirm_Expire {
            get {
                return ResourceManager.GetString("vldconfirm_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อความแจ้ง Hot Feat หมดอายุแล้ว.
        /// </summary>
        public static string vldconfirm_ExpireHot {
            get {
                return ResourceManager.GetString("vldconfirm_ExpireHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you want to move product category ?.
        /// </summary>
        public static string vldconfirm_move_procate {
            get {
                return ResourceManager.GetString("vldconfirm_move_procate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the category that delete or move the product before removing categories..
        /// </summary>
        public static string vldconfirm_moveanddel_cate {
            get {
                return ResourceManager.GetString("vldconfirm_moveanddel_cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อความแจ้ง Gold Member Package ใกล้หมดอายุ.
        /// </summary>
        public static string vldconfirm_NearExpire {
            get {
                return ResourceManager.GetString("vldconfirm_NearExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อความแจ้ง Hot Feat ใกล้หมดอายุ.
        /// </summary>
        public static string vldconfirm_NearExpireHot {
            get {
                return ResourceManager.GetString("vldconfirm_NearExpireHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to restore this item..
        /// </summary>
        public static string vldconfirm_restore {
            get {
                return ResourceManager.GetString("vldconfirm_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to restore all item..
        /// </summary>
        public static string vldconfirm_restore_all {
            get {
                return ResourceManager.GetString("vldconfirm_restore_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill data is incorrect..
        /// </summary>
        public static string vlddata_incorrect {
            get {
                return ResourceManager.GetString("vlddata_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string vlddear {
            get {
                return ResourceManager.GetString("vlddear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Message Successfully..
        /// </summary>
        public static string vlddel_msg_success {
            get {
                return ResourceManager.GetString("vlddel_msg_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfully..
        /// </summary>
        public static string vlddel_success {
            get {
                return ResourceManager.GetString("vlddel_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful delete data. Please try again later..
        /// </summary>
        public static string vlddel_unsuccess {
            get {
                return ResourceManager.GetString("vlddel_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter details..
        /// </summary>
        public static string vlddetails {
            get {
                return ResourceManager.GetString("vlddetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is  duplicate..
        /// </summary>
        public static string vlddisplayname_exists {
            get {
                return ResourceManager.GetString("vlddisplayname_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft has been saved..
        /// </summary>
        public static string vlddraft_success {
            get {
                return ResourceManager.GetString("vlddraft_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to junk..
        /// </summary>
        public static string vlddrag_to_junk {
            get {
                return ResourceManager.GetString("vlddrag_to_junk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate keyword.
        /// </summary>
        public static string vldduplicatekeyword {
            get {
                return ResourceManager.GetString("vldduplicatekeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit successfully..
        /// </summary>
        public static string vldedit_success {
            get {
                return ResourceManager.GetString("vldedit_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful edit data. Please try again later..
        /// </summary>
        public static string vldedit_unsuccess {
            get {
                return ResourceManager.GetString("vldedit_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is  duplicate..
        /// </summary>
        public static string vldemail_exists {
            get {
                return ResourceManager.GetString("vldemail_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email does not match the request..
        /// </summary>
        public static string vldemail_request {
            get {
                return ResourceManager.GetString("vldemail_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date can not be less then the start date.
        /// </summary>
        public static string vldenddate {
            get {
                return ResourceManager.GetString("vldenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy end date must be greater than the current date..
        /// </summary>
        public static string vldenddate_buy {
            get {
                return ResourceManager.GetString("vldenddate_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data (English only)..
        /// </summary>
        public static string vldengonly {
            get {
                return ResourceManager.GetString("vldengonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the message..
        /// </summary>
        public static string vldenter_message {
            get {
                return ResourceManager.GetString("vldenter_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the recipient..
        /// </summary>
        public static string vldenter_recipient {
            get {
                return ResourceManager.GetString("vldenter_recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your search..
        /// </summary>
        public static string vldenter_search {
            get {
                return ResourceManager.GetString("vldenter_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a subject..
        /// </summary>
        public static string vldenter_subject {
            get {
                return ResourceManager.GetString("vldenter_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string vldenter_validemail {
            get {
                return ResourceManager.GetString("vldenter_validemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Because.
        /// </summary>
        public static string vlderror_because {
            get {
                return ResourceManager.GetString("vlderror_because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list as a favorite..
        /// </summary>
        public static string vldfav_success {
            get {
                return ResourceManager.GetString("vldfav_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite Success All.
        /// </summary>
        public static string vldfavoriteall {
            get {
                return ResourceManager.GetString("vldfavoriteall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your email..
        /// </summary>
        public static string vldfill_youremail {
            get {
                return ResourceManager.GetString("vldfill_youremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your message..
        /// </summary>
        public static string vldfill_yourmessage {
            get {
                return ResourceManager.GetString("vldfill_yourmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your name..
        /// </summary>
        public static string vldfill_yourname {
            get {
                return ResourceManager.GetString("vldfill_yourname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your phone number..
        /// </summary>
        public static string vldfill_yourphone {
            get {
                return ResourceManager.GetString("vldfill_yourphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a correct email address..
        /// </summary>
        public static string vldfix_format_email {
            get {
                return ResourceManager.GetString("vldfix_format_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only numbers..
        /// </summary>
        public static string vldfix_format_number {
            get {
                return ResourceManager.GetString("vldfix_format_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a correct phone number..
        /// </summary>
        public static string vldfix_format_phone {
            get {
                return ResourceManager.GetString("vldfix_format_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support file .jpg .jpeg .png only..
        /// </summary>
        public static string vldfix_format_picture {
            get {
                return ResourceManager.GetString("vldfix_format_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your format is not correct..
        /// </summary>
        public static string vldformaterror {
            get {
                return ResourceManager.GetString("vldformaterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can Get Quotes them.
        /// </summary>
        public static string vldget_quo {
            get {
                return ResourceManager.GetString("vldget_quo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide more details..
        /// </summary>
        public static string vldhide_moredetail {
            get {
                return ResourceManager.GetString("vldhide_moredetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Select 5 Images Only..
        /// </summary>
        public static string vldimg_fix5 {
            get {
                return ResourceManager.GetString("vldimg_fix5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input correct number..
        /// </summary>
        public static string vldinput_correct_number {
            get {
                return ResourceManager.GetString("vldinput_correct_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter keyword..
        /// </summary>
        public static string vldinput_keyword {
            get {
                return ResourceManager.GetString("vldinput_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full! You can add product to maximum 20 items. Please upgrade gold member for get more..
        /// </summary>
        public static string vldismaxproduct {
            get {
                return ResourceManager.GetString("vldismaxproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 10 characters..
        /// </summary>
        public static string vldless_10char {
            get {
                return ResourceManager.GetString("vldless_10char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 2 characters..
        /// </summary>
        public static string vldless_2char {
            get {
                return ResourceManager.GetString("vldless_2char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lease enter at least 3 characters..
        /// </summary>
        public static string vldless_3char {
            get {
                return ResourceManager.GetString("vldless_3char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lease enter at least 4 characters..
        /// </summary>
        public static string vldless_4char {
            get {
                return ResourceManager.GetString("vldless_4char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 5 characters..
        /// </summary>
        public static string vldless_5char {
            get {
                return ResourceManager.GetString("vldless_5char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 6 characters..
        /// </summary>
        public static string vldless_6char {
            get {
                return ResourceManager.GetString("vldless_6char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lease enter at least 9 characters..
        /// </summary>
        public static string vldless_9char {
            get {
                return ResourceManager.GetString("vldless_9char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief description of the article is too long. Please try again later..
        /// </summary>
        public static string vldlmessagelength {
            get {
                return ResourceManager.GetString("vldlmessagelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked : Can&apos;t be saved..
        /// </summary>
        public static string vldlocked {
            get {
                return ResourceManager.GetString("vldlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Importance Successfully..
        /// </summary>
        public static string vldmark_importance_success {
            get {
                return ResourceManager.GetString("vldmark_importance_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Unimportance Successfully..
        /// </summary>
        public static string vldmark_unimportance_success {
            get {
                return ResourceManager.GetString("vldmark_unimportance_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Unread Successfully..
        /// </summary>
        public static string vldmark_unread_success {
            get {
                return ResourceManager.GetString("vldmark_unread_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill max 5 words..
        /// </summary>
        public static string vldmax_word5 {
            get {
                return ResourceManager.GetString("vldmax_word5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can upload up to 3 images..
        /// </summary>
        public static string vldmaximg_3 {
            get {
                return ResourceManager.GetString("vldmaximg_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อความไม่เกิน 500 ตัวอักษร.
        /// </summary>
        public static string vldmessage500length {
            get {
                return ResourceManager.GetString("vldmessage500length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 4 char and no more than 12 char..
        /// </summary>
        public static string vldmin_4_max_12char {
            get {
                return ResourceManager.GetString("vldmin_4_max_12char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 4 char and no more than 16 char..
        /// </summary>
        public static string vldmin_4_max_16char {
            get {
                return ResourceManager.GetString("vldmin_4_max_16char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 4 char and no more than 20 char..
        /// </summary>
        public static string vldmin_4_max_20char {
            get {
                return ResourceManager.GetString("vldmin_4_max_20char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 6 char and no more than 12 char..
        /// </summary>
        public static string vldmin_6_max_12char {
            get {
                return ResourceManager.GetString("vldmin_6_max_12char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 6 char and no more than 20 char..
        /// </summary>
        public static string vldmin_6_max_20char {
            get {
                return ResourceManager.GetString("vldmin_6_max_20char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least 1 image.
        /// </summary>
        public static string vldminimg_1 {
            get {
                return ResourceManager.GetString("vldminimg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than 10 characters..
        /// </summary>
        public static string vldmore_10char {
            get {
                return ResourceManager.GetString("vldmore_10char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than 50 characters..
        /// </summary>
        public static string vldmore_50char {
            get {
                return ResourceManager.GetString("vldmore_50char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than 5 characters..
        /// </summary>
        public static string vldmore_5char {
            get {
                return ResourceManager.GetString("vldmore_5char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the category the product before removing. Category so that the number is 0..
        /// </summary>
        public static string vldmove_pro_zero {
            get {
                return ResourceManager.GetString("vldmove_pro_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are sure to move this product into the trash..
        /// </summary>
        public static string vldmovepro_to_trash {
            get {
                return ResourceManager.GetString("vldmovepro_to_trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string vldno_data {
            get {
                return ResourceManager.GetString("vldno_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected item..
        /// </summary>
        public static string vldno_item_selected {
            get {
                return ResourceManager.GetString("vldno_item_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because product lose  quality. And the content is missing..
        /// </summary>
        public static string vldnoapprove_pro {
            get {
                return ResourceManager.GetString("vldnoapprove_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email was not found in the system..
        /// </summary>
        public static string vldnoemail {
            get {
                return ResourceManager.GetString("vldnoemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonSpecific.
        /// </summary>
        public static string vldnon_specific {
            get {
                return ResourceManager.GetString("vldnon_specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specific Keyword.
        /// </summary>
        public static string vldnon_specific_keyword {
            get {
                return ResourceManager.GetString("vldnon_specific_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found this company..
        /// </summary>
        public static string vldnot_found_company {
            get {
                return ResourceManager.GetString("vldnot_found_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the data to be deleted..
        /// </summary>
        public static string vldnotice_del {
            get {
                return ResourceManager.GetString("vldnotice_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user was not found in the system..
        /// </summary>
        public static string vldnouser {
            get {
                return ResourceManager.GetString("vldnouser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email does not exist in the system..
        /// </summary>
        public static string vldnouseremail {
            get {
                return ResourceManager.GetString("vldnouseremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string vldother {
            get {
                return ResourceManager.GetString("vldother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot go to over page..
        /// </summary>
        public static string vldoverpage {
            get {
                return ResourceManager.GetString("vldoverpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string vldpass_not_same {
            get {
                return ResourceManager.GetString("vldpass_not_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect..
        /// </summary>
        public static string vldpassword_incorrect {
            get {
                return ResourceManager.GetString("vldpassword_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the account name transfer..
        /// </summary>
        public static string vldpayeraccname {
            get {
                return ResourceManager.GetString("vldpayeraccname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the account number, the transferor..
        /// </summary>
        public static string vldpayeraccno {
            get {
                return ResourceManager.GetString("vldpayeraccno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful payment. Approval of the Admin..
        /// </summary>
        public static string vldpayment_success {
            get {
                return ResourceManager.GetString("vldpayment_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Groupname have already..
        /// </summary>
        public static string vldpgroup_already {
            get {
                return ResourceManager.GetString("vldpgroup_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select..
        /// </summary>
        public static string vldplease_select {
            get {
                return ResourceManager.GetString("vldplease_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Favorite..
        /// </summary>
        public static string vldplease_select_fav {
            get {
                return ResourceManager.GetString("vldplease_select_fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please SignIn..
        /// </summary>
        public static string vldplease_signin {
            get {
                return ResourceManager.GetString("vldplease_signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please unlock the security system..
        /// </summary>
        public static string vldplease_unlock {
            get {
                return ResourceManager.GetString("vldplease_unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This productname have already.
        /// </summary>
        public static string vldpname_already {
            get {
                return ResourceManager.GetString("vldpname_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string vldpreview {
            get {
                return ResourceManager.GetString("vldpreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product bid.
        /// </summary>
        public static string vldpro_bid {
            get {
                return ResourceManager.GetString("vldpro_bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Link.
        /// </summary>
        public static string vldproductlink {
            get {
                return ResourceManager.GetString("vldproductlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reject, because sent this quotation already.
        /// </summary>
        public static string vldquotationreject {
            get {
                return ResourceManager.GetString("vldquotationreject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was unsuccessful. Please try again later..
        /// </summary>
        public static string vldrequest_unsuccessful {
            get {
                return ResourceManager.GetString("vldrequest_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string vldrequired {
            get {
                return ResourceManager.GetString("vldrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all required fields..
        /// </summary>
        public static string vldrequired_complete {
            get {
                return ResourceManager.GetString("vldrequired_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose image..
        /// </summary>
        public static string vldrequired_img {
            get {
                return ResourceManager.GetString("vldrequired_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request product successfully..
        /// </summary>
        public static string vldrreqestbid {
            get {
                return ResourceManager.GetString("vldrreqestbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the same value again..
        /// </summary>
        public static string vldsame_value {
            get {
                return ResourceManager.GetString("vldsame_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success, Wait for admin approve..
        /// </summary>
        public static string vldsave_buyleadSuccess {
            get {
                return ResourceManager.GetString("vldsave_buyleadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save has successfully..
        /// </summary>
        public static string vldsave_success {
            get {
                return ResourceManager.GetString("vldsave_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful save data. Please try again later..
        /// </summary>
        public static string vldsave_unsuccess {
            get {
                return ResourceManager.GetString("vldsave_unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search buylead.
        /// </summary>
        public static string vldsearch_buylead {
            get {
                return ResourceManager.GetString("vldsearch_buylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search product.
        /// </summary>
        public static string vldsearch_product {
            get {
                return ResourceManager.GetString("vldsearch_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search supplier.
        /// </summary>
        public static string vldsearch_supplier {
            get {
                return ResourceManager.GetString("vldsearch_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see more.
        /// </summary>
        public static string vldseemore {
            get {
                return ResourceManager.GetString("vldseemore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string vldselect_all {
            get {
                return ResourceManager.GetString("vldselect_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected company. Please select that you want company..
        /// </summary>
        public static string vldselect_company {
            get {
                return ResourceManager.GetString("vldselect_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Account type..
        /// </summary>
        public static string vldselectacctype {
            get {
                return ResourceManager.GetString("vldselectacctype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a article type..
        /// </summary>
        public static string vldselectarticletype {
            get {
                return ResourceManager.GetString("vldselectarticletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Attributes..
        /// </summary>
        public static string vldselectattributes {
            get {
                return ResourceManager.GetString("vldselectattributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Bank..
        /// </summary>
        public static string vldselectbank {
            get {
                return ResourceManager.GetString("vldselectbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a business type..
        /// </summary>
        public static string vldselectbiztype {
            get {
                return ResourceManager.GetString("vldselectbiztype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select category.
        /// </summary>
        public static string vldselectcate {
            get {
                return ResourceManager.GetString("vldselectcate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select category level 1.
        /// </summary>
        public static string vldselectcateLV1 {
            get {
                return ResourceManager.GetString("vldselectcateLV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select category level 2.
        /// </summary>
        public static string vldselectcateLV2 {
            get {
                return ResourceManager.GetString("vldselectcateLV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select category level 3.
        /// </summary>
        public static string vldselectcateLV3 {
            get {
                return ResourceManager.GetString("vldselectcateLV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a company level..
        /// </summary>
        public static string vldselectcomplevel {
            get {
                return ResourceManager.GetString("vldselectcomplevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Country..
        /// </summary>
        public static string vldselectcountry {
            get {
                return ResourceManager.GetString("vldselectcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select district..
        /// </summary>
        public static string vldselectdistrict {
            get {
                return ResourceManager.GetString("vldselectdistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category..
        /// </summary>
        public static string vldselectjobcate {
            get {
                return ResourceManager.GetString("vldselectjobcate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select job type..
        /// </summary>
        public static string vldselectjobtype {
            get {
                return ResourceManager.GetString("vldselectjobtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select province..
        /// </summary>
        public static string vldselectprovince {
            get {
                return ResourceManager.GetString("vldselectprovince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the level of education..
        /// </summary>
        public static string vldselectreqeducation {
            get {
                return ResourceManager.GetString("vldselectreqeducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select experience..
        /// </summary>
        public static string vldselectreqexp {
            get {
                return ResourceManager.GetString("vldselectreqexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a service type..
        /// </summary>
        public static string vldselectservicetype {
            get {
                return ResourceManager.GetString("vldselectservicetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data success. Can history of data at menu myAssignLead..
        /// </summary>
        public static string vldsend_purchas_success {
            get {
                return ResourceManager.GetString("vldsend_purchas_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message successfully..
        /// </summary>
        public static string vldsend_success {
            get {
                return ResourceManager.GetString("vldsend_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data to customers successfully..
        /// </summary>
        public static string vldsenddata_success {
            get {
                return ResourceManager.GetString("vldsenddata_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message ....
        /// </summary>
        public static string vldsendingmsg {
            get {
                return ResourceManager.GetString("vldsendingmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data to Member successfully..
        /// </summary>
        public static string vldsendtouser_success {
            get {
                return ResourceManager.GetString("vldsendtouser_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your data finished.
        /// </summary>
        public static string vldsendyoudata_success {
            get {
                return ResourceManager.GetString("vldsendyoudata_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide bar to the right. for send message..
        /// </summary>
        public static string vldslidesendmsg {
            get {
                return ResourceManager.GetString("vldslidesendmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific.
        /// </summary>
        public static string vldspecific {
            get {
                return ResourceManager.GetString("vldspecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date can not be greater then the end date.
        /// </summary>
        public static string vldstartdate {
            get {
                return ResourceManager.GetString("vldstartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your suggestions..
        /// </summary>
        public static string vldthk_suggestion {
            get {
                return ResourceManager.GetString("vldthk_suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked : Can be saved..
        /// </summary>
        public static string vldunlocked {
            get {
                return ResourceManager.GetString("vldunlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You  purchase a maximum of only one feature product Name. Please upgrade gold member to increase the order..
        /// </summary>
        public static string vldUpgoldtoPuschase {
            get {
                return ResourceManager.GetString("vldUpgoldtoPuschase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ouikumstorage.blob.core.windows.net/upload/.
        /// </summary>
        public static string vldurl_upload {
            get {
                return ResourceManager.GetString("vldurl_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account is incorrect..
        /// </summary>
        public static string vlduser_incorrect {
            get {
                return ResourceManager.GetString("vlduser_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username does not match the request..
        /// </summary>
        public static string vlduser_request {
            get {
                return ResourceManager.GetString("vlduser_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is duplicate..
        /// </summary>
        public static string vldusername_exists {
            get {
                return ResourceManager.GetString("vldusername_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see Get Quotes the product has.
        /// </summary>
        public static string vldview_quo {
            get {
                return ResourceManager.GetString("vldview_quo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the bids from the seller through your contacts..
        /// </summary>
        public static string vldwaitbid {
            get {
                return ResourceManager.GetString("vldwaitbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can wait contact you via your email..
        /// </summary>
        public static string vldwaitemail {
            get {
                return ResourceManager.GetString("vldwaitemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2BThai.com.
        /// </summary>
        public static string vldweb {
            get {
                return ResourceManager.GetString("vldweb", resourceCulture);
            }
        }
    }
}
