//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message_Center {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_Center() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Message Center", typeof(Message_Center).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Draft.
        /// </summary>
        public static string btnDraft {
            get {
                return ResourceManager.GetString("btnDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string btnFavorite {
            get {
                return ResourceManager.GetString("btnFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string btnForward {
            get {
                return ResourceManager.GetString("btnForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string btnFrom {
            get {
                return ResourceManager.GetString("btnFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Read.
        /// </summary>
        public static string btnMark_read {
            get {
                return ResourceManager.GetString("btnMark_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Unread.
        /// </summary>
        public static string btnMark_unread {
            get {
                return ResourceManager.GetString("btnMark_unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Unread.
        /// </summary>
        public static string btnMark_unread1 {
            get {
                return ResourceManager.GetString("btnMark_unread1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnMsgDelete {
            get {
                return ResourceManager.GetString("btnMsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        public static string btnNew_msg {
            get {
                return ResourceManager.GetString("btnNew_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string btnReply {
            get {
                return ResourceManager.GetString("btnReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string btnSendMessage {
            get {
                return ResourceManager.GetString("btnSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string btnSignOut {
            get {
                return ResourceManager.GetString("btnSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string btnTo {
            get {
                return ResourceManager.GetString("btnTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More Details.
        /// </summary>
        public static string btnView_more_details {
            get {
                return ResourceManager.GetString("btnView_more_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string colSelectAll {
            get {
                return ResourceManager.GetString("colSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        public static string lblAnonymous {
            get {
                return ResourceManager.GetString("lblAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach another file.
        /// </summary>
        public static string lblAtt_more_file {
            get {
                return ResourceManager.GetString("lblAtt_more_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach a file.
        /// </summary>
        public static string lblAttach_file {
            get {
                return ResourceManager.GetString("lblAttach_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view.
        /// </summary>
        public static string lblClickToView {
            get {
                return ResourceManager.GetString("lblClickToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to mark important.
        /// </summary>
        public static string lblconfirm_mark_importance {
            get {
                return ResourceManager.GetString("lblconfirm_mark_importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to want to mark unread.
        /// </summary>
        public static string lblconfirm_mark_unread {
            get {
                return ResourceManager.GetString("lblconfirm_mark_unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Company.
        /// </summary>
        public static string lblContactComp {
            get {
                return ResourceManager.GetString("lblContactComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacted.
        /// </summary>
        public static string lblContacted {
            get {
                return ResourceManager.GetString("lblContacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact us immediately..
        /// </summary>
        public static string lblContactImmediately {
            get {
                return ResourceManager.GetString("lblContactImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string lblDear {
            get {
                return ResourceManager.GetString("lblDear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand detail.
        /// </summary>
        public static string lblDemandDetail {
            get {
                return ResourceManager.GetString("lblDemandDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เนื่องด้วยทางเว็บไซต์ Ouikum.com ได้มีการลงโฆษณาและทำการประชาสัมพันธ์สินค้าของบริษัทท่าน ผ่านเว็บไซต์Ouikum.com.
        /// </summary>
        public static string lblDemandMatchYourProduct {
            get {
                return ResourceManager.GetString("lblDemandMatchYourProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เว็บไซต์ที่เป็นตัวกลางในการติดต่อซื้อขายสินค้าธุรกิจออนไลน์ (E-Marketplace) ขนาดใหญ่ เพื่อให้สินค้าของบริษัทท่านมียอดขายที่เพิ่มขึ้น เราได้ทำการประชาสัมพันธ์ให้ท่านอย่างเต็มที่.
        /// </summary>
        public static string lblDemandMatchYourProduct2 {
            get {
                return ResourceManager.GetString("lblDemandMatchYourProduct2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string lblDraftbox {
            get {
                return ResourceManager.GetString("lblDraftbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note :.
        /// </summary>
        public static string lblEmailNote {
            get {
                return ResourceManager.GetString("lblEmailNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This E-mail simply is a message from the website Ouikum.com. Please! Do not reply its back.
        /// </summary>
        public static string lblEmailNoteDetail {
            get {
                return ResourceManager.GetString("lblEmailNoteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending a mail. Please try again..
        /// </summary>
        public static string lblErrorSendMail {
            get {
                return ResourceManager.GetString("lblErrorSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string lblFavorite {
            get {
                return ResourceManager.GetString("lblFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string lblFeedback {
            get {
                return ResourceManager.GetString("lblFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for view demand. And modify or add your trading infomation..
        /// </summary>
        public static string lblForViewDemand {
            get {
                return ResourceManager.GetString("lblForViewDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the score for us (10 score is a maximum level)..
        /// </summary>
        public static string lblGiveScore1 {
            get {
                return ResourceManager.GetString("lblGiveScore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many level of Ouikum.com useful for your business?.
        /// </summary>
        public static string lblGiveScore2 {
            get {
                return ResourceManager.GetString("lblGiveScore2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ได้ขอข้อมูลไว้กับทาง.
        /// </summary>
        public static string lblHasReqInfo {
            get {
                return ResourceManager.GetString("lblHasReqInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to enable it again. Please contact Ouikum.comm..
        /// </summary>
        public static string lblIfEnableAgain {
            get {
                return ResourceManager.GetString("lblIfEnableAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to renew membership. Please informed.
        /// </summary>
        public static string lblIfRenewMembership {
            get {
                return ResourceManager.GetString("lblIfRenewMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string lblImportance {
            get {
                return ResourceManager.GetString("lblImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string lblInbox {
            get {
                return ResourceManager.GetString("lblInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information for Ouikum.com customer only.
        /// </summary>
        public static string lblInfoForCustomer {
            get {
                return ResourceManager.GetString("lblInfoForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would like to inform that You has registered as member through the administrators at.
        /// </summary>
        public static string lblInformRegMember {
            get {
                return ResourceManager.GetString("lblInformRegMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has introduced a job.
        /// </summary>
        public static string lblIntroduceJob {
            get {
                return ResourceManager.GetString("lblIntroduceJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Message.
        /// </summary>
        public static string lblipt_msg {
            get {
                return ResourceManager.GetString("lblipt_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view a job&apos;s detail on the links below..
        /// </summary>
        public static string lblJobDetail_Link_below {
            get {
                return ResourceManager.GetString("lblJobDetail_Link_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblKhun {
            get {
                return ResourceManager.GetString("lblKhun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string lblMarkImportance {
            get {
                return ResourceManager.GetString("lblMarkImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 5 mb.
        /// </summary>
        public static string lblMaximum5mb {
            get {
                return ResourceManager.GetString("lblMaximum5mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has sent a message to you via Ouikum.com as follows :.
        /// </summary>
        public static string lblMsg_follows {
            get {
                return ResourceManager.GetString("lblMsg_follows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message  Center.
        /// </summary>
        public static string lblMsgcenter {
            get {
                return ResourceManager.GetString("lblMsgcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from customer.
        /// </summary>
        public static string lblMsgFromCustomer {
            get {
                return ResourceManager.GetString("lblMsgFromCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        public static string lblNew_msg {
            get {
                return ResourceManager.GetString("lblNew_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contact.
        /// </summary>
        public static string lblNoContact {
            get {
                return ResourceManager.GetString("lblNoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        public static string lblNoresult {
            get {
                return ResourceManager.GetString("lblNoresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Aunction.
        /// </summary>
        public static string lblOnlineAuction {
            get {
                return ResourceManager.GetString("lblOnlineAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เท่านั้น.
        /// </summary>
        public static string lblOnly {
            get {
                return ResourceManager.GetString("lblOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify.
        /// </summary>
        public static string lblPleaseSpecify {
            get {
                return ResourceManager.GetString("lblPleaseSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post buying Link.
        /// </summary>
        public static string lblPostBuyingLink {
            get {
                return ResourceManager.GetString("lblPostBuyingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Compare.
        /// </summary>
        public static string lblProductCompare {
            get {
                return ResourceManager.GetString("lblProductCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product demand.
        /// </summary>
        public static string lblProductDemand {
            get {
                return ResourceManager.GetString("lblProductDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Link.
        /// </summary>
        public static string lblProductLink {
            get {
                return ResourceManager.GetString("lblProductLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string lblRecipient {
            get {
                return ResourceManager.GetString("lblRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Quotation.
        /// </summary>
        public static string lblReqQuotaion {
            get {
                return ResourceManager.GetString("lblReqQuotaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Contact.
        /// </summary>
        public static string lblSelect_Contact {
            get {
                return ResourceManager.GetString("lblSelect_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Contact.
        /// </summary>
        public static string lblSend_contact {
            get {
                return ResourceManager.GetString("lblSend_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to friends.
        /// </summary>
        public static string lblSend_to_friend {
            get {
                return ResourceManager.GetString("lblSend_to_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send box.
        /// </summary>
        public static string lblSendbox {
            get {
                return ResourceManager.GetString("lblSendbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Date.
        /// </summary>
        public static string lblSendDate {
            get {
                return ResourceManager.GetString("lblSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string lblSender {
            get {
                return ResourceManager.GetString("lblSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a Message to Admin.
        /// </summary>
        public static string lblSendMsgAdmin {
            get {
                return ResourceManager.GetString("lblSendMsgAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to Friends.
        /// </summary>
        public static string lblSendtofriend {
            get {
                return ResourceManager.GetString("lblSendtofriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since.
        /// </summary>
        public static string lblSince {
            get {
                return ResourceManager.GetString("lblSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yours sincerely,.
        /// </summary>
        public static string lblSincerely {
            get {
                return ResourceManager.GetString("lblSincerely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sir or Madam.
        /// </summary>
        public static string lblSir {
            get {
                return ResourceManager.GetString("lblSir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 new message from.
        /// </summary>
        public static string lblSubject_p1 {
            get {
                return ResourceManager.GetString("lblSubject_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Ouikum.com.
        /// </summary>
        public static string lblSubject_p2 {
            get {
                return ResourceManager.GetString("lblSubject_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacted you via b2bthai.com.
        /// </summary>
        public static string lblSuject_3 {
            get {
                return ResourceManager.GetString("lblSuject_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want in B2BThai.com?.
        /// </summary>
        public static string lblSurveyQuestion {
            get {
                return ResourceManager.GetString("lblSurveyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like Ouikum.com has.
        /// </summary>
        public static string lblSystem_has {
            get {
                return ResourceManager.GetString("lblSystem_has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouikum.com Team.
        /// </summary>
        public static string lblTeam {
            get {
                return ResourceManager.GetString("lblTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your suggestions..
        /// </summary>
        public static string lblThanksForSuggest {
            get {
                return ResourceManager.GetString("lblThanksForSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that.
        /// </summary>
        public static string lblThatYou {
            get {
                return ResourceManager.GetString("lblThatYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an information.
        /// </summary>
        public static string lblThisInfoSupplier {
            get {
                return ResourceManager.GetString("lblThisInfoSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to you..
        /// </summary>
        public static string lblToYou {
            get {
                return ResourceManager.GetString("lblToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can sign in to make changes or add  traded information and view contact information through the message center..
        /// </summary>
        public static string lblUserDescription {
            get {
                return ResourceManager.GetString("lblUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via b2bthai.com.
        /// </summary>
        public static string lblVia {
            get {
                return ResourceManager.GetString("lblVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Message.
        /// </summary>
        public static string lblView_msg {
            get {
                return ResourceManager.GetString("lblView_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view the supplier information at.
        /// </summary>
        public static string lblViewSupplierAt {
            get {
                return ResourceManager.GetString("lblViewSupplierAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view your message report and your request price.
        /// </summary>
        public static string lblViewYour_Msg_RequestPrice {
            get {
                return ResourceManager.GetString("lblViewYour_Msg_RequestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to reply message via B2BThai.com. Please click .
        /// </summary>
        public static string lblWantToViewMsg {
            get {
                return ResourceManager.GetString("lblWantToViewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string lblWelcomeTo {
            get {
                return ResourceManager.GetString("lblWelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        public static string lblYourAccount {
            get {
                return ResourceManager.GetString("lblYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment.
        /// </summary>
        public static string lblYourComment {
            get {
                return ResourceManager.GetString("lblYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string lblYourEmail {
            get {
                return ResourceManager.GetString("lblYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string lblYourName {
            get {
                return ResourceManager.GetString("lblYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your online store.
        /// </summary>
        public static string lblYourOnlineStore {
            get {
                return ResourceManager.GetString("lblYourOnlineStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Default/images/img_LogoB2BThai120x74.png.
        /// </summary>
        public static string path_logo {
            get {
                return ResourceManager.GetString("path_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend&apos;s e-mail.
        /// </summary>
        public static string pdFriendEmail {
            get {
                return ResourceManager.GetString("pdFriendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend&apos;s name.
        /// </summary>
        public static string pdFriendName {
            get {
                return ResourceManager.GetString("pdFriendName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string pdFromEmail {
            get {
                return ResourceManager.GetString("pdFromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string pdFromName {
            get {
                return ResourceManager.GetString("pdFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to company.
        /// </summary>
        public static string pdToCompany {
            get {
                return ResourceManager.GetString("pdToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to email.
        /// </summary>
        public static string pdToEmail {
            get {
                return ResourceManager.GetString("pdToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone Number.
        /// </summary>
        public static string pdYourPhone {
            get {
                return ResourceManager.GetString("pdYourPhone", resourceCulture);
            }
        }
    }
}
