//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Order {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Order() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Order", typeof(Order).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string lblAcc_name {
            get {
                return ResourceManager.GetString("lblAcc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string lblAcc_type {
            get {
                return ResourceManager.GetString("lblAcc_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string lblAccNum {
            get {
                return ResourceManager.GetString("lblAccNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Payment.
        /// </summary>
        public static string lblAllPayment {
            get {
                return ResourceManager.GetString("lblAllPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already purchased. Please check your order.
        /// </summary>
        public static string lblAlreadyPurchased {
            get {
                return ResourceManager.GetString("lblAlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of transfer.
        /// </summary>
        public static string lblAmountTransfer {
            get {
                return ResourceManager.GetString("lblAmountTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string lblApproved {
            get {
                return ResourceManager.GetString("lblApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Payment.
        /// </summary>
        public static string lblApprovePayment {
            get {
                return ResourceManager.GetString("lblApprovePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string lblBack_en {
            get {
                return ResourceManager.GetString("lblBack_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baht.
        /// </summary>
        public static string lblBaht {
            get {
                return ResourceManager.GetString("lblBaht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string lblBank_name {
            get {
                return ResourceManager.GetString("lblBank_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string lblBranch {
            get {
                return ResourceManager.GetString("lblBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string lblBuy {
            get {
                return ResourceManager.GetString("lblBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string lblBuyNow {
            get {
                return ResourceManager.GetString("lblBuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel_en {
            get {
                return ResourceManager.GetString("lblCancel_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this order.
        /// </summary>
        public static string lblCancelOrder {
            get {
                return ResourceManager.GetString("lblCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Order.
        /// </summary>
        public static string lblCancelOrder_en {
            get {
                return ResourceManager.GetString("lblCancelOrder_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this package.
        /// </summary>
        public static string lblCancelPackage {
            get {
                return ResourceManager.GetString("lblCancelPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges added data.
        /// </summary>
        public static string lblChargesAddedData {
            get {
                return ResourceManager.GetString("lblChargesAddedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose just.
        /// </summary>
        public static string lblChoosejust {
            get {
                return ResourceManager.GetString("lblChoosejust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string lblComments {
            get {
                return ResourceManager.GetString("lblComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of payment.
        /// </summary>
        public static string lblDatePayment {
            get {
                return ResourceManager.GetString("lblDatePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date - time of transfer.
        /// </summary>
        public static string lblDatetimeTransfer {
            get {
                return ResourceManager.GetString("lblDatetimeTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of transfer.
        /// </summary>
        public static string lblDateTransfer {
            get {
                return ResourceManager.GetString("lblDateTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string lblDiscount {
            get {
                return ResourceManager.GetString("lblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Month/Year.
        /// </summary>
        public static string lblDMY {
            get {
                return ResourceManager.GetString("lblDMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit success, go to payment.
        /// </summary>
        public static string lbleditpayment {
            get {
                return ResourceManager.GetString("lbleditpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format.
        /// </summary>
        public static string lblFileFormat {
            get {
                return ResourceManager.GetString("lblFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpg .jpeg .png.
        /// </summary>
        public static string lblFileFormat2 {
            get {
                return ResourceManager.GetString("lblFileFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out information of payment.
        /// </summary>
        public static string lblFillPayment {
            get {
                return ResourceManager.GetString("lblFillPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in detail of payment source.
        /// </summary>
        public static string lblFillPaymentInfo {
            get {
                return ResourceManager.GetString("lblFillPaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in detail of payment destination.
        /// </summary>
        public static string lblFillPaymentInfo2 {
            get {
                return ResourceManager.GetString("lblFillPaymentInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out for tax invoice information / receipt.
        /// </summary>
        public static string lblFillTax_Receipt {
            get {
                return ResourceManager.GetString("lblFillTax_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Package.
        /// </summary>
        public static string lblFreePackage {
            get {
                return ResourceManager.GetString("lblFreePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Package.
        /// </summary>
        public static string lblGoldPackage {
            get {
                return ResourceManager.GetString("lblGoldPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string lblHere {
            get {
                return ResourceManager.GetString("lblHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string lblItem_en {
            get {
                return ResourceManager.GetString("lblItem_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need.
        /// </summary>
        public static string lblNeedTax {
            get {
                return ResourceManager.GetString("lblNeedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string lblNext {
            get {
                return ResourceManager.GetString("lblNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Need.
        /// </summary>
        public static string lblNotNeedTax {
            get {
                return ResourceManager.GetString("lblNotNeedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 picture.
        /// </summary>
        public static string lblOnePic {
            get {
                return ResourceManager.GetString("lblOnePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only.
        /// </summary>
        public static string lblOnly {
            get {
                return ResourceManager.GetString("lblOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string lblOrder {
            get {
                return ResourceManager.GetString("lblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string lblOrder_en {
            get {
                return ResourceManager.GetString("lblOrder_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Code.
        /// </summary>
        public static string lblOrderCode {
            get {
                return ResourceManager.GetString("lblOrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string lblOrderDate {
            get {
                return ResourceManager.GetString("lblOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Detail Code.
        /// </summary>
        public static string lblOrderDetailCode {
            get {
                return ResourceManager.GetString("lblOrderDetailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order placement  Feature product.
        /// </summary>
        public static string lblOrderFeat {
            get {
                return ResourceManager.GetString("lblOrderFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order placement  Hot product.
        /// </summary>
        public static string lblOrderHot {
            get {
                return ResourceManager.GetString("lblOrderHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order List.
        /// </summary>
        public static string lblOrderList {
            get {
                return ResourceManager.GetString("lblOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No..
        /// </summary>
        public static string lblOrderNo {
            get {
                return ResourceManager.GetString("lblOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Information.
        /// </summary>
        public static string lblOrdersInfo {
            get {
                return ResourceManager.GetString("lblOrdersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order success, go to payment.
        /// </summary>
        public static string lblOrdersuccessPayment {
            get {
                return ResourceManager.GetString("lblOrdersuccessPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package List and Price.
        /// </summary>
        public static string lblPackage_Price {
            get {
                return ResourceManager.GetString("lblPackage_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        public static string lblPackageName {
            get {
                return ResourceManager.GetString("lblPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string lblPaid {
            get {
                return ResourceManager.GetString("lblPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment informant.
        /// </summary>
        public static string lblPayInformant {
            get {
                return ResourceManager.GetString("lblPayInformant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string lblPayment {
            get {
                return ResourceManager.GetString("lblPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string lblPayment_en {
            get {
                return ResourceManager.GetString("lblPayment_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment amount.
        /// </summary>
        public static string lblPaymentAmount {
            get {
                return ResourceManager.GetString("lblPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Code.
        /// </summary>
        public static string lblPaymentCode {
            get {
                return ResourceManager.GetString("lblPaymentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment information.
        /// </summary>
        public static string lblPaymentInfo {
            get {
                return ResourceManager.GetString("lblPaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment List.
        /// </summary>
        public static string lblPaymentList {
            get {
                return ResourceManager.GetString("lblPaymentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment List.
        /// </summary>
        public static string lblPaymentList2 {
            get {
                return ResourceManager.GetString("lblPaymentList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please  check payment again.
        /// </summary>
        public static string lblPleasecheckpayment {
            get {
                return ResourceManager.GetString("lblPleasecheckpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products and costs.
        /// </summary>
        public static string lblProducts_Costs {
            get {
                return ResourceManager.GetString("lblProducts_Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate advertising.
        /// </summary>
        public static string lblRateAds {
            get {
                return ResourceManager.GetString("lblRateAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Fees.
        /// </summary>
        public static string lblRegisFees {
            get {
                return ResourceManager.GetString("lblRegisFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request approval a new document.
        /// </summary>
        public static string lblReqApprovNewDoc {
            get {
                return ResourceManager.GetString("lblReqApprovNewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Reciept.
        /// </summary>
        public static string lblReqReciept {
            get {
                return ResourceManager.GetString("lblReqReciept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Package.
        /// </summary>
        public static string lblSelectPackage {
            get {
                return ResourceManager.GetString("lblSelectPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service fee payment.
        /// </summary>
        public static string lblServiceFeePayment {
            get {
                return ResourceManager.GetString("lblServiceFeePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Package.
        /// </summary>
        public static string lblServicePackage {
            get {
                return ResourceManager.GetString("lblServicePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slip transfer.
        /// </summary>
        public static string lblSlipTransfer {
            get {
                return ResourceManager.GetString("lblSlipTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1 Select Package.
        /// </summary>
        public static string lblStep1 {
            get {
                return ResourceManager.GetString("lblStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step2 Order.
        /// </summary>
        public static string lblStep2 {
            get {
                return ResourceManager.GetString("lblStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step3 Payment.
        /// </summary>
        public static string lblStep3 {
            get {
                return ResourceManager.GetString("lblStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit_en {
            get {
                return ResourceManager.GetString("lblSubmit_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Payment.
        /// </summary>
        public static string lblSubmitPayment_en {
            get {
                return ResourceManager.GetString("lblSubmitPayment_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string lblSumPaymentInfo {
            get {
                return ResourceManager.GetString("lblSumPaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Price.
        /// </summary>
        public static string lblSumPrice_en {
            get {
                return ResourceManager.GetString("lblSumPrice_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax invoice.
        /// </summary>
        public static string lblTax {
            get {
                return ResourceManager.GetString("lblTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string lblTime {
            get {
                return ResourceManager.GetString("lblTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of transfer (Approx).
        /// </summary>
        public static string lblTimeTransfer {
            get {
                return ResourceManager.GetString("lblTimeTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank transfer from.
        /// </summary>
        public static string lblTransferFrom {
            get {
                return ResourceManager.GetString("lblTransferFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer information.
        /// </summary>
        public static string lblTransferInfo {
            get {
                return ResourceManager.GetString("lblTransferInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank transfer to.
        /// </summary>
        public static string lblTransferTo {
            get {
                return ResourceManager.GetString("lblTransferTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers to account.
        /// </summary>
        public static string lblTransferToAcc {
            get {
                return ResourceManager.GetString("lblTransferToAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string lblUnpaid {
            get {
                return ResourceManager.GetString("lblUnpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Gold Member.
        /// </summary>
        public static string lblUpgradeGold {
            get {
                return ResourceManager.GetString("lblUpgradeGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT 7%.
        /// </summary>
        public static string lblVat7 {
            get {
                return ResourceManager.GetString("lblVat7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order package in B2BThai.com.
        /// </summary>
        public static string tltPagekage {
            get {
                return ResourceManager.GetString("tltPagekage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have orders pending payment.
        /// </summary>
        public static string txtPendingPayment {
            get {
                return ResourceManager.GetString("txtPendingPayment", resourceCulture);
            }
        }
    }
}
