//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Product {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Product() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Product", typeof(Product).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Compare.
        /// </summary>
        public static string btnAdd_to_Compare {
            get {
                return ResourceManager.GetString("btnAdd_to_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorite.
        /// </summary>
        public static string btnAdd_to_Favorite {
            get {
                return ResourceManager.GetString("btnAdd_to_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is selected.
        /// </summary>
        public static string btnItem_selected {
            get {
                return ResourceManager.GetString("btnItem_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string btnProduct_Compare {
            get {
                return ResourceManager.GetString("btnProduct_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Price.
        /// </summary>
        public static string btnRequestPrice {
            get {
                return ResourceManager.GetString("btnRequestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnRequestPrice2 {
            get {
                return ResourceManager.GetString("btnRequestPrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a buying request.
        /// </summary>
        public static string lblAdd_Buylead {
            get {
                return ResourceManager.GetString("lblAdd_Buylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more key word.
        /// </summary>
        public static string lblAdd_kw {
            get {
                return ResourceManager.GetString("lblAdd_kw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more details..
        /// </summary>
        public static string lbladd_moreDetail {
            get {
                return ResourceManager.GetString("lbladd_moreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a new product.
        /// </summary>
        public static string lblAdd_product {
            get {
                return ResourceManager.GetString("lblAdd_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Compare.
        /// </summary>
        public static string lblAddCompare {
            get {
                return ResourceManager.GetString("lblAddCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorite.
        /// </summary>
        public static string lblAddFavorite {
            get {
                return ResourceManager.GetString("lblAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Select and drag for setting image.
        /// </summary>
        public static string lblAddImg_Guide1 {
            get {
                return ResourceManager.GetString("lblAddImg_Guide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximize 5 MB.
        /// </summary>
        public static string lblAddImg_Guide2 {
            get {
                return ResourceManager.GetString("lblAddImg_Guide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For beautiful display, New images should be square..
        /// </summary>
        public static string lblAddImg_Guide3 {
            get {
                return ResourceManager.GetString("lblAddImg_Guide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Products Unlimited.
        /// </summary>
        public static string lblAddUnlimitedProducts {
            get {
                return ResourceManager.GetString("lblAddUnlimitedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Product.
        /// </summary>
        public static string lblAll_pro {
            get {
                return ResourceManager.GetString("lblAll_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Buying Request.
        /// </summary>
        public static string lblAllBuylead {
            get {
                return ResourceManager.GetString("lblAllBuylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Product Category.
        /// </summary>
        public static string lblAllCatePro {
            get {
                return ResourceManager.GetString("lblAllCatePro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All item.
        /// </summary>
        public static string lblAllitem {
            get {
                return ResourceManager.GetString("lblAllitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Product.
        /// </summary>
        public static string lblApproveProduct {
            get {
                return ResourceManager.GetString("lblApproveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoMobile.
        /// </summary>
        public static string lblAutoMobile {
            get {
                return ResourceManager.GetString("lblAutoMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baht.
        /// </summary>
        public static string lblBaht {
            get {
                return ResourceManager.GetString("lblBaht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangkok Metropolis.
        /// </summary>
        public static string lblBangkok {
            get {
                return ResourceManager.GetString("lblBangkok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bids Product.
        /// </summary>
        public static string lblBidProduct {
            get {
                return ResourceManager.GetString("lblBidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangkok.
        /// </summary>
        public static string lblBkk {
            get {
                return ResourceManager.GetString("lblBkk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying Request.
        /// </summary>
        public static string lblBuylead {
            get {
                return ResourceManager.GetString("lblBuylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying Request.
        /// </summary>
        public static string lblBuylead_eng {
            get {
                return ResourceManager.GetString("lblBuylead_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying Request  List.
        /// </summary>
        public static string lblBuyleadList {
            get {
                return ResourceManager.GetString("lblBuyleadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string lblCate {
            get {
                return ResourceManager.GetString("lblCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,B,C,D.
        /// </summary>
        public static string lblCategories1 {
            get {
                return ResourceManager.GetString("lblCategories1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E,F,G,H.
        /// </summary>
        public static string lblCategories2 {
            get {
                return ResourceManager.GetString("lblCategories2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I,J,K,L.
        /// </summary>
        public static string lblCategories3 {
            get {
                return ResourceManager.GetString("lblCategories3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M,N,O,P.
        /// </summary>
        public static string lblCategories4 {
            get {
                return ResourceManager.GetString("lblCategories4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q,R,S,T.
        /// </summary>
        public static string lblCategories5 {
            get {
                return ResourceManager.GetString("lblCategories5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U,V,W, X.
        /// </summary>
        public static string lblCategories6 {
            get {
                return ResourceManager.GetString("lblCategories6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y,Z.
        /// </summary>
        public static string lblCategories7 {
            get {
                return ResourceManager.GetString("lblCategories7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Category.
        /// </summary>
        public static string lblCateLV1 {
            get {
                return ResourceManager.GetString("lblCateLV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Category.
        /// </summary>
        public static string lblCateLV2 {
            get {
                return ResourceManager.GetString("lblCateLV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string lblCateLV3 {
            get {
                return ResourceManager.GetString("lblCateLV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Category.
        /// </summary>
        public static string lblCateofAll {
            get {
                return ResourceManager.GetString("lblCateofAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string lblCatePro {
            get {
                return ResourceManager.GetString("lblCatePro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W, X,Y,Z.
        /// </summary>
        public static string lblCharsearch {
            get {
                return ResourceManager.GetString("lblCharsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new category.
        /// </summary>
        public static string lblChg_Cate {
            get {
                return ResourceManager.GetString("lblChg_Cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all result.
        /// </summary>
        public static string lblClearallsearch {
            get {
                return ResourceManager.GetString("lblClearallsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for upload photo.
        /// </summary>
        public static string lblClickForUploadPhoto {
            get {
                return ResourceManager.GetString("lblClickForUploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Setting.
        /// </summary>
        public static string lblCloseSetting {
            get {
                return ResourceManager.GetString("lblCloseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer,Software.
        /// </summary>
        public static string lblComp_Soft {
            get {
                return ResourceManager.GetString("lblComp_Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Product.
        /// </summary>
        public static string lblComparePro {
            get {
                return ResourceManager.GetString("lblComparePro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete category..
        /// </summary>
        public static string lblconfirm_del_catepro {
            get {
                return ResourceManager.GetString("lblconfirm_del_catepro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Sell Product.
        /// </summary>
        public static string lblConfirmSellProduct {
            get {
                return ResourceManager.GetString("lblConfirmSellProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction &amp; Real Estate.
        /// </summary>
        public static string lblConstruction_Realestate {
            get {
                return ResourceManager.GetString("lblConstruction_Realestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Electronics.
        /// </summary>
        public static string lblConsumer_Electronics {
            get {
                return ResourceManager.GetString("lblConsumer_Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Supplier.
        /// </summary>
        public static string lblContact_Supplier {
            get {
                return ResourceManager.GetString("lblContact_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Supplier.
        /// </summary>
        public static string lblContact_Supplier1 {
            get {
                return ResourceManager.GetString("lblContact_Supplier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Count.
        /// </summary>
        public static string lblContactCount {
            get {
                return ResourceManager.GetString("lblContactCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Supplier.
        /// </summary>
        public static string lblContactSupplier {
            get {
                return ResourceManager.GetString("lblContactSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original category will be deleted. After moving product is finished..
        /// </summary>
        public static string lbldel_af_move {
            get {
                return ResourceManager.GetString("lbldel_af_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information demand sell.
        /// </summary>
        public static string lblDemand_sell {
            get {
                return ResourceManager.GetString("lblDemand_sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Drag Product Here&quot;.
        /// </summary>
        public static string lblDragProductHere {
            get {
                return ResourceManager.GetString("lblDragProductHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category Level 1.
        /// </summary>
        public static string lbledit_cateLV1 {
            get {
                return ResourceManager.GetString("lbledit_cateLV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category Level 2.
        /// </summary>
        public static string lbledit_cateLV2 {
            get {
                return ResourceManager.GetString("lbledit_cateLV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category Level 3.
        /// </summary>
        public static string lbledit_cateLV3 {
            get {
                return ResourceManager.GetString("lbledit_cateLV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category Type.
        /// </summary>
        public static string lbledit_catetype {
            get {
                return ResourceManager.GetString("lbledit_catetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Recycle Bin.
        /// </summary>
        public static string lblEmptybin {
            get {
                return ResourceManager.GetString("lblEmptybin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feat.
        /// </summary>
        public static string lblFeat {
            get {
                return ResourceManager.GetString("lblFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string lblFeature {
            get {
                return ResourceManager.GetString("lblFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Product.
        /// </summary>
        public static string lblFeature_Pro {
            get {
                return ResourceManager.GetString("lblFeature_Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format.
        /// </summary>
        public static string lblFile_Format {
            get {
                return ResourceManager.GetString("lblFile_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of file .pdf .xlsx .docx .jpg .jpgs.
        /// </summary>
        public static string lblformatfile {
            get {
                return ResourceManager.GetString("lblformatfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        public static string lblFurniture {
            get {
                return ResourceManager.GetString("lblFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Product.
        /// </summary>
        public static string lblGeneral_Product {
            get {
                return ResourceManager.GetString("lblGeneral_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware &amp; Tools.
        /// </summary>
        public static string lblHardware_Tools {
            get {
                return ResourceManager.GetString("lblHardware_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Menu.
        /// </summary>
        public static string lblHidemenu {
            get {
                return ResourceManager.GetString("lblHidemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest volume production.
        /// </summary>
        public static string lblHigh_value_Product {
            get {
                return ResourceManager.GetString("lblHigh_value_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High volume production.
        /// </summary>
        public static string lblHighProduction {
            get {
                return ResourceManager.GetString("lblHighProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home,Garden.
        /// </summary>
        public static string lblHome_Garden {
            get {
                return ResourceManager.GetString("lblHome_Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string lblHot {
            get {
                return ResourceManager.GetString("lblHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Product.
        /// </summary>
        public static string lblHot_Pro {
            get {
                return ResourceManager.GetString("lblHot_Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Premium Product.
        /// </summary>
        public static string lblHotFeat {
            get {
                return ResourceManager.GetString("lblHotFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Product.
        /// </summary>
        public static string lblIndustry {
            get {
                return ResourceManager.GetString("lblIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string lblItem {
            get {
                return ResourceManager.GetString("lblItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk.
        /// </summary>
        public static string lblJunk {
            get {
                return ResourceManager.GetString("lblJunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key word.
        /// </summary>
        public static string lblKey_word {
            get {
                return ResourceManager.GetString("lblKey_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key word.
        /// </summary>
        public static string lblKeyword {
            get {
                return ResourceManager.GetString("lblKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastest Product.
        /// </summary>
        public static string lblLastCreateProduct {
            get {
                return ResourceManager.GetString("lblLastCreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasted Edit Product.
        /// </summary>
        public static string lblLastModifyProduct {
            get {
                return ResourceManager.GetString("lblLastModifyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string lblLayout {
            get {
                return ResourceManager.GetString("lblLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machinery.
        /// </summary>
        public static string lblMachinery {
            get {
                return ResourceManager.GetString("lblMachinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main picture.
        /// </summary>
        public static string lblmain_pic {
            get {
                return ResourceManager.GetString("lblmain_pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of products you can Upload..
        /// </summary>
        public static string lblMax_upload_product {
            get {
                return ResourceManager.GetString("lblMax_upload_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Product.
        /// </summary>
        public static string lblMaxProduct {
            get {
                return ResourceManager.GetString("lblMaxProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mininum Order Unit.
        /// </summary>
        public static string lblMinimum_Unit {
            get {
                return ResourceManager.GetString("lblMinimum_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Buying Request.
        /// </summary>
        public static string lblMng_buylead {
            get {
                return ResourceManager.GetString("lblMng_buylead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Junk.
        /// </summary>
        public static string lblMng_BuyleadJunk {
            get {
                return ResourceManager.GetString("lblMng_BuyleadJunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Category.
        /// </summary>
        public static string lblMng_Category {
            get {
                return ResourceManager.GetString("lblMng_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Feature Product.
        /// </summary>
        public static string lblMng_FeaPro {
            get {
                return ResourceManager.GetString("lblMng_FeaPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Hot Product.
        /// </summary>
        public static string lblMng_Hot {
            get {
                return ResourceManager.GetString("lblMng_Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Junk.
        /// </summary>
        public static string lblMng_Junk {
            get {
                return ResourceManager.GetString("lblMng_Junk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Menu.
        /// </summary>
        public static string lblMng_menu {
            get {
                return ResourceManager.GetString("lblMng_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Premium.
        /// </summary>
        public static string lblMng_Premium {
            get {
                return ResourceManager.GetString("lblMng_Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Product.
        /// </summary>
        public static string lblMng_product {
            get {
                return ResourceManager.GetString("lblMng_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Recommend Product.
        /// </summary>
        public static string lblMng_Recommend {
            get {
                return ResourceManager.GetString("lblMng_Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details..
        /// </summary>
        public static string lblMore_Detail {
            get {
                return ResourceManager.GetString("lblMore_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More_Product.
        /// </summary>
        public static string lblMore_Product {
            get {
                return ResourceManager.GetString("lblMore_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move product before deleting product category..
        /// </summary>
        public static string lblmove_del_proandcate {
            get {
                return ResourceManager.GetString("lblmove_del_proandcate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is in the original category. Will be moved to the new category..
        /// </summary>
        public static string lblmovetonewcate {
            get {
                return ResourceManager.GetString("lblmovetonewcate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Trash.
        /// </summary>
        public static string lblMoveToTrash {
            get {
                return ResourceManager.GetString("lblMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new  Location of product..
        /// </summary>
        public static string lblnewlocation_pro {
            get {
                return ResourceManager.GetString("lblnewlocation_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        public static string lblNewProduct {
            get {
                return ResourceManager.GetString("lblNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Feature Product.
        /// </summary>
        public static string lblNoFeatPro {
            get {
                return ResourceManager.GetString("lblNoFeatPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found group.
        /// </summary>
        public static string lblNoProductGroup {
            get {
                return ResourceManager.GetString("lblNoProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the original category are not deleted..
        /// </summary>
        public static string lblnotdel_catepro {
            get {
                return ResourceManager.GetString("lblnotdel_catepro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found category.
        /// </summary>
        public static string lblNotfoundCate {
            get {
                return ResourceManager.GetString("lblNotfoundCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of employees.
        /// </summary>
        public static string lblNum_of_emp {
            get {
                return ResourceManager.GetString("lblNum_of_emp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office &amp; School Supplies.
        /// </summary>
        public static string lblOffice_Schoolsupplies {
            get {
                return ResourceManager.GetString("lblOffice_Schoolsupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only.
        /// </summary>
        public static string lblOnly {
            get {
                return ResourceManager.GetString("lblOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string lblOrigin {
            get {
                return ResourceManager.GetString("lblOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment and Shipping.
        /// </summary>
        public static string lblPay_Ship {
            get {
                return ResourceManager.GetString("lblPay_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a new product.
        /// </summary>
        public static string lblPost_NewProduct {
            get {
                return ResourceManager.GetString("lblPost_NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post your product.
        /// </summary>
        public static string lblPost_you_Product {
            get {
                return ResourceManager.GetString("lblPost_you_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Buying the latest products..
        /// </summary>
        public static string lblPostBuyinglatest {
            get {
                return ResourceManager.GetString("lblPostBuyinglatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Product.
        /// </summary>
        public static string lblPremiumproduct {
            get {
                return ResourceManager.GetString("lblPremiumproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary product information.
        /// </summary>
        public static string lblPreProductInfo {
            get {
                return ResourceManager.GetString("lblPreProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string lblPreview {
            get {
                return ResourceManager.GetString("lblPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price / Piece.
        /// </summary>
        public static string lblPrice_one {
            get {
                return ResourceManager.GetString("lblPrice_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale.
        /// </summary>
        public static string lblPricesend {
            get {
                return ResourceManager.GetString("lblPricesend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string lblPro {
            get {
                return ResourceManager.GetString("lblPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string lblPro_Cate {
            get {
                return ResourceManager.GetString("lblPro_Cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        public static string lblPro_Group {
            get {
                return ResourceManager.GetString("lblPro_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string lblPro_name {
            get {
                return ResourceManager.GetString("lblPro_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Unit.
        /// </summary>
        public static string lblPro_SelectUnit {
            get {
                return ResourceManager.GetString("lblPro_SelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Unit.
        /// </summary>
        public static string lblPro_Unit {
            get {
                return ResourceManager.GetString("lblPro_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string lblProduct {
            get {
                return ResourceManager.GetString("lblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        public static string lblProduct_Detail {
            get {
                return ResourceManager.GetString("lblProduct_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string lblProduct_details {
            get {
                return ResourceManager.GetString("lblProduct_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of product is full. Your package can display only 20 items.
        /// </summary>
        public static string lblProduct_Full {
            get {
                return ResourceManager.GetString("lblProduct_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description.
        /// </summary>
        public static string lblProduct_in_detail {
            get {
                return ResourceManager.GetString("lblProduct_in_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products related this suppliers.
        /// </summary>
        public static string lblProduct_relate {
            get {
                return ResourceManager.GetString("lblProduct_relate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product and service.
        /// </summary>
        public static string lblProductAndService {
            get {
                return ResourceManager.GetString("lblProductAndService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string lblProductCode {
            get {
                return ResourceManager.GetString("lblProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Gallery.
        /// </summary>
        public static string lblProductGallery {
            get {
                return ResourceManager.GetString("lblProductGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product image.
        /// </summary>
        public static string lblProductImage {
            get {
                return ResourceManager.GetString("lblProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product infomation more.
        /// </summary>
        public static string lblProductInfoMore {
            get {
                return ResourceManager.GetString("lblProductInfoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string lblProductList {
            get {
                return ResourceManager.GetString("lblProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product for service.
        /// </summary>
        public static string lblProductService {
            get {
                return ResourceManager.GetString("lblProductService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Store.
        /// </summary>
        public static string lblProductStore {
            get {
                return ResourceManager.GetString("lblProductStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Unit / Piece.
        /// </summary>
        public static string lblQtyUnit_one {
            get {
                return ResourceManager.GetString("lblQtyUnit_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblQuick_Detail {
            get {
                return ResourceManager.GetString("lblQuick_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of recommend product is full..
        /// </summary>
        public static string lblRecommend_Full {
            get {
                return ResourceManager.GetString("lblRecommend_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products with this supplier.
        /// </summary>
        public static string lblRelate_pro_supplier {
            get {
                return ResourceManager.GetString("lblRelate_pro_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Supplier.
        /// </summary>
        public static string lblRelatedSupplier {
            get {
                return ResourceManager.GetString("lblRelatedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Price.
        /// </summary>
        public static string lblReq_Quo {
            get {
                return ResourceManager.GetString("lblReq_Quo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select as least 1 image.
        /// </summary>
        public static string lblRequireImg {
            get {
                return ResourceManager.GetString("lblRequireImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save List No.
        /// </summary>
        public static string lblSaveListNo {
            get {
                return ResourceManager.GetString("lblSaveListNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search product.
        /// </summary>
        public static string lblSearchstore {
            get {
                return ResourceManager.GetString("lblSearchstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security &amp; Protection.
        /// </summary>
        public static string lblSecurity_Protection {
            get {
                return ResourceManager.GetString("lblSecurity_Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See larger image.
        /// </summary>
        public static string lblSeelargerimage {
            get {
                return ResourceManager.GetString("lblSeelargerimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location new product..
        /// </summary>
        public static string lblselect_location_pro {
            get {
                return ResourceManager.GetString("lblselect_location_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select product group.
        /// </summary>
        public static string lblSelectGroup {
            get {
                return ResourceManager.GetString("lblSelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Supplier.
        /// </summary>
        public static string lblSelectSupplier {
            get {
                return ResourceManager.GetString("lblSelectSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Product.
        /// </summary>
        public static string lblsell_product {
            get {
                return ResourceManager.GetString("lblsell_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Conditions.
        /// </summary>
        public static string lblSellingConditions {
            get {
                return ResourceManager.GetString("lblSellingConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Rate.
        /// </summary>
        public static string lblServiceRate {
            get {
                return ResourceManager.GetString("lblServiceRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting display options.
        /// </summary>
        public static string lblSett_display_opt {
            get {
                return ResourceManager.GetString("lblSett_display_opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing menu.
        /// </summary>
        public static string lblSetting {
            get {
                return ResourceManager.GetString("lblSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string lblShow_Topic {
            get {
                return ResourceManager.GetString("lblShow_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Menu.
        /// </summary>
        public static string lblShowmenu {
            get {
                return ResourceManager.GetString("lblShowmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more similar product.
        /// </summary>
        public static string lblsimilarproduct {
            get {
                return ResourceManager.GetString("lblsimilarproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string lblSize {
            get {
                return ResourceManager.GetString("lblSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Product.
        /// </summary>
        public static string lblSortProduct {
            get {
                return ResourceManager.GetString("lblSortProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier List.
        /// </summary>
        public static string lblSupplierlist {
            get {
                return ResourceManager.GetString("lblSupplierlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เทคนิคการประกาศขายสินค้า.
        /// </summary>
        public static string lblTechnique {
            get {
                return ResourceManager.GetString("lblTechnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Condition.
        /// </summary>
        public static string lblTermCondition {
            get {
                return ResourceManager.GetString("lblTermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string lblUSD {
            get {
                return ResourceManager.GetString("lblUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View count.
        /// </summary>
        public static string lblViewCount {
            get {
                return ResourceManager.GetString("lblViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblvowel1 {
            get {
                return ResourceManager.GetString("lblvowel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblvowel2 {
            get {
                return ResourceManager.GetString("lblvowel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale.
        /// </summary>
        public static string lblWholesale {
            get {
                return ResourceManager.GetString("lblWholesale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraband.
        /// </summary>
        public static string validContraband {
            get {
                return ResourceManager.GetString("validContraband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not match product.
        /// </summary>
        public static string validDataImgNotMatchData {
            get {
                return ResourceManager.GetString("validDataImgNotMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is missing / not complete.
        /// </summary>
        public static string validDataMissing_NotCollect {
            get {
                return ResourceManager.GetString("validDataMissing_NotCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other remark.
        /// </summary>
        public static string validOtherRemark {
            get {
                return ResourceManager.GetString("validOtherRemark", resourceCulture);
            }
        }
    }
}
