//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Purchasing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Purchasing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Purchasing", typeof(Purchasing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สร้างข้อมูล.
        /// </summary>
        public static string btnAssignLead {
            get {
                return ResourceManager.GetString("btnAssignLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lead.
        /// </summary>
        public static string btnCreate_emLead {
            get {
                return ResourceManager.GetString("btnCreate_emLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import  ข้อมูลเริ่มต้น.
        /// </summary>
        public static string btnImportemLead {
            get {
                return ResourceManager.GetString("btnImportemLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือก.
        /// </summary>
        public static string btnImportToLead {
            get {
                return ResourceManager.GetString("btnImportToLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูล.
        /// </summary>
        public static string btnMsgDelete {
            get {
                return ResourceManager.GetString("btnMsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More Company.
        /// </summary>
        public static string lblAddMoreCompany {
            get {
                return ResourceManager.GetString("lblAddMoreCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Lead Report.
        /// </summary>
        public static string lblAssignReport {
            get {
                return ResourceManager.GetString("lblAssignReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2Bthai Account.
        /// </summary>
        public static string lblB2BthaiAccount {
            get {
                return ResourceManager.GetString("lblB2BthaiAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying request relate.
        /// </summary>
        public static string lblBuyingrequestrelate {
            get {
                return ResourceManager.GetString("lblBuyingrequestrelate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบริษัท.
        /// </summary>
        public static string lblByCompName {
            get {
                return ResourceManager.GetString("lblByCompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบริษัท / ชื่อร้าน.
        /// </summary>
        public static string lblCompName {
            get {
                return ResourceManager.GetString("lblCompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล์ผู้ติดต่อ.
        /// </summary>
        public static string lblContactEmail {
            get {
                return ResourceManager.GetString("lblContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ติดต่อ.
        /// </summary>
        public static string lblContactName {
            get {
                return ResourceManager.GetString("lblContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรผู้ติดต่อ.
        /// </summary>
        public static string lblContactTel {
            get {
                return ResourceManager.GetString("lblContactTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลลูกค้า.
        /// </summary>
        public static string lblCustomerProfile {
            get {
                return ResourceManager.GetString("lblCustomerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลเริ่มต้น.
        /// </summary>
        public static string lblemLead {
            get {
                return ResourceManager.GetString("lblemLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import emLead.
        /// </summary>
        public static string lblImportemLead {
            get {
                return ResourceManager.GetString("lblImportemLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead  Name.
        /// </summary>
        public static string lblLeadName {
            get {
                return ResourceManager.GetString("lblLeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Option.
        /// </summary>
        public static string lblLeadOption {
            get {
                return ResourceManager.GetString("lblLeadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadReport.
        /// </summary>
        public static string lblLeadReport {
            get {
                return ResourceManager.GetString("lblLeadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Type.
        /// </summary>
        public static string lblMemberType {
            get {
                return ResourceManager.GetString("lblMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งแล้ว.
        /// </summary>
        public static string lblmyAssignLead {
            get {
                return ResourceManager.GetString("lblmyAssignLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Company.
        /// </summary>
        public static string lblNoCompany {
            get {
                return ResourceManager.GetString("lblNoCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Center.
        /// </summary>
        public static string lblPurchasingCenter {
            get {
                return ResourceManager.GetString("lblPurchasingCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Member.
        /// </summary>
        public static string lblRegisterMember {
            get {
                return ResourceManager.GetString("lblRegisterMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายชื่อผู้ขายสินค้า -.
        /// </summary>
        public static string lblReport_title {
            get {
                return ResourceManager.GetString("lblReport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการข้อมูลผู้ขายสินค้า.
        /// </summary>
        public static string lblReport1 {
            get {
                return ResourceManager.GetString("lblReport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่คุณ.
        /// </summary>
        public static string lblReport2 {
            get {
                return ResourceManager.GetString("lblReport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ได้ขอข้อมูลไว้กับทาง B2BThai.com.
        /// </summary>
        public static string lblReport3 {
            get {
                return ResourceManager.GetString("lblReport3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Email.
        /// </summary>
        public static string lblSendToEmail {
            get {
                return ResourceManager.GetString("lblSendToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Default emLead.
        /// </summary>
        public static string lblSetDefaultLead {
            get {
                return ResourceManager.GetString("lblSetDefaultLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string lbltest {
            get {
                return ResourceManager.GetString("lbltest", resourceCulture);
            }
        }
    }
}
