//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web.Ouikum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Quotation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Quotation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Ouikum.Quotation", typeof(Quotation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel for sale..
        /// </summary>
        public static string btnCancleforSale {
            get {
                return ResourceManager.GetString("btnCancleforSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Quotation.
        /// </summary>
        public static string btnDeleteBid {
            get {
                return ResourceManager.GetString("btnDeleteBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock..
        /// </summary>
        public static string btnnoStock {
            get {
                return ResourceManager.GetString("btnnoStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quatity of product is not enough.
        /// </summary>
        public static string btnPronot_enough {
            get {
                return ResourceManager.GetString("btnPronot_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string btnReject {
            get {
                return ResourceManager.GetString("btnReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach with .pdf.
        /// </summary>
        public static string lblAttach_pdf {
            get {
                return ResourceManager.GetString("lblAttach_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Remark.
        /// </summary>
        public static string lblAttach_Remark {
            get {
                return ResourceManager.GetString("lblAttach_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string lblBid {
            get {
                return ResourceManager.GetString("lblBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid sale.
        /// </summary>
        public static string lblBid_sale {
            get {
                return ResourceManager.GetString("lblBid_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid back.
        /// </summary>
        public static string lblBidback {
            get {
                return ResourceManager.GetString("lblBidback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid By.
        /// </summary>
        public static string lblBidBy {
            get {
                return ResourceManager.GetString("lblBidBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidder.
        /// </summary>
        public static string lblBidder {
            get {
                return ResourceManager.GetString("lblBidder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidder Information.
        /// </summary>
        public static string lblBidinfo {
            get {
                return ResourceManager.GetString("lblBidinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Bid.
        /// </summary>
        public static string lblClosebid {
            get {
                return ResourceManager.GetString("lblClosebid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us..
        /// </summary>
        public static string lblContactUs {
            get {
                return ResourceManager.GetString("lblContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find product price information or bid product via B2BThai.com here.
        /// </summary>
        public static string lblDes_QuotationLink {
            get {
                return ResourceManager.GetString("lblDes_QuotationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the quotation via B2BThai.com at.
        /// </summary>
        public static string lblDes_QuotationLink2 {
            get {
                return ResourceManager.GetString("lblDes_QuotationLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string lblDiscount {
            get {
                return ResourceManager.GetString("lblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End bid this product.
        /// </summary>
        public static string lblEndbidproduct {
            get {
                return ResourceManager.GetString("lblEndbidproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Price.
        /// </summary>
        public static string lblEstimate_Price {
            get {
                return ResourceManager.GetString("lblEstimate_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in form completely..
        /// </summary>
        public static string lblFill_from_complete {
            get {
                return ResourceManager.GetString("lblFill_from_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For suppliers who are interested. You able to bid by contact at.
        /// </summary>
        public static string lblForSupplier {
            get {
                return ResourceManager.GetString("lblForSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string lblImportant {
            get {
                return ResourceManager.GetString("lblImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string lblInbox {
            get {
                return ResourceManager.GetString("lblInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last bid.
        /// </summary>
        public static string lblLastBid {
            get {
                return ResourceManager.GetString("lblLastBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Low price.
        /// </summary>
        public static string lblLowPrice {
            get {
                return ResourceManager.GetString("lblLowPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myRequest Price.
        /// </summary>
        public static string lblmyRequest {
            get {
                return ResourceManager.GetString("lblmyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string lblOption {
            get {
                return ResourceManager.GetString("lblOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per piece.
        /// </summary>
        public static string lblPricePerPiece {
            get {
                return ResourceManager.GetString("lblPricePerPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a product that match  to needs of the buyer. From the list below, you can.
        /// </summary>
        public static string lblProductmatchneedbuyer {
            get {
                return ResourceManager.GetString("lblProductmatchneedbuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string lblProductName {
            get {
                return ResourceManager.GetString("lblProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string lblQty {
            get {
                return ResourceManager.GetString("lblQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Date.
        /// </summary>
        public static string lblQuo_date {
            get {
                return ResourceManager.GetString("lblQuo_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Attach.
        /// </summary>
        public static string lblQuoAttach {
            get {
                return ResourceManager.GetString("lblQuoAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Code.
        /// </summary>
        public static string lblQuoCode {
            get {
                return ResourceManager.GetString("lblQuoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Quotation Message Successful.
        /// </summary>
        public static string lblQuoSentMsg {
            get {
                return ResourceManager.GetString("lblQuoSentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Price.
        /// </summary>
        public static string lblQuotation {
            get {
                return ResourceManager.GetString("lblQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation.
        /// </summary>
        public static string lblQuotation_ {
            get {
                return ResourceManager.GetString("lblQuotation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Detail.
        /// </summary>
        public static string lblQuotation_Detail {
            get {
                return ResourceManager.GetString("lblQuotation_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Price.
        /// </summary>
        public static string lblQuotation1 {
            get {
                return ResourceManager.GetString("lblQuotation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has offered price.
        /// </summary>
        public static string lblQuotationDetailFollow1 {
            get {
                return ResourceManager.GetString("lblQuotationDetailFollow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via B2BThai.com the details as follows..
        /// </summary>
        public static string lblQuotationDetailFollow2 {
            get {
                return ResourceManager.GetString("lblQuotationDetailFollow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หากคุณมีสินค้าที่ตรงกับความต้องการของผู้ซื้อ คุณสามารถเสนอราคาขายให้กับผู้ซื้อได้ | เสนอราคาสินค้า | B2BThai.com.
        /// </summary>
        public static string lblQuotationMetaDesc {
            get {
                return ResourceManager.GetString("lblQuotationMetaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าที่มีผู้ขอราคาซื้อล่าสุด | B2BThai.com.
        /// </summary>
        public static string lblQuotationMetaKeyword {
            get {
                return ResourceManager.GetString("lblQuotationMetaKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Report.
        /// </summary>
        public static string lblQuotationReport {
            get {
                return ResourceManager.GetString("lblQuotationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Quotation for.
        /// </summary>
        public static string lblQuotationSubject1 {
            get {
                return ResourceManager.GetString("lblQuotationSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2BThai.com.
        /// </summary>
        public static string lblQuotationSubject2 {
            get {
                return ResourceManager.GetString("lblQuotationSubject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestPrice | B2BThai.com.
        /// </summary>
        public static string lblQuotationTitle {
            get {
                return ResourceManager.GetString("lblQuotationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Bid.
        /// </summary>
        public static string lblReplybid {
            get {
                return ResourceManager.GetString("lblReplybid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can bid Reply already Want to new bid again ?.
        /// </summary>
        public static string lblReplybid_and_new {
            get {
                return ResourceManager.GetString("lblReplybid_and_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีระบบที่ช่วยให้คุณสามารถติดตามข้อความร้องขอของคุณย้อนหลังได้ตลอดเวลา.
        /// </summary>
        public static string lblReplytext1 {
            get {
                return ResourceManager.GetString("lblReplytext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สามารถเก็บข้อความร้องขอหรือข้อความเสนอราคาให้เป็นข้อความที่สำคัญของคุณได้.
        /// </summary>
        public static string lblReplytext2 {
            get {
                return ResourceManager.GetString("lblReplytext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Product List.
        /// </summary>
        public static string lblReq_List {
            get {
                return ResourceManager.GetString("lblReq_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Request Price.
        /// </summary>
        public static string lblReq_Price {
            get {
                return ResourceManager.GetString("lblReq_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested your product.
        /// </summary>
        public static string lblReqDetailFollow1 {
            get {
                return ResourceManager.GetString("lblReqDetailFollow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price via B2BThai.com. The details as follows :.
        /// </summary>
        public static string lblReqDetailFollow2 {
            get {
                return ResourceManager.GetString("lblReqDetailFollow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งอีเมล์ไปยังผู้ขายที่เกี่ยวข้อง.
        /// </summary>
        public static string lblReqIsSupplierRelated {
            get {
                return ResourceManager.GetString("lblReqIsSupplierRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับข้อมูลสินค้าที่เกี่ยวข้องเพิ่มเติม.
        /// </summary>
        public static string lblReqIsTrackRelated {
            get {
                return ResourceManager.GetString("lblReqIsTrackRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone request your.
        /// </summary>
        public static string lblReqPriceSubject1 {
            get {
                return ResourceManager.GetString("lblReqPriceSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price - B2BThai.com.
        /// </summary>
        public static string lblReqPriceSubject2 {
            get {
                return ResourceManager.GetString("lblReqPriceSubject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public (Supplier can bid).
        /// </summary>
        public static string lblReqPublic {
            get {
                return ResourceManager.GetString("lblReqPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Price  related to product below.
        /// </summary>
        public static string lblRqsTitle {
            get {
                return ResourceManager.GetString("lblRqsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your information before sending.
        /// </summary>
        public static string lblRqsWorn {
            get {
                return ResourceManager.GetString("lblRqsWorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Approval.
        /// </summary>
        public static string lblSale_Approval {
            get {
                return ResourceManager.GetString("lblSale_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Email.
        /// </summary>
        public static string lblSale_Email {
            get {
                return ResourceManager.GetString("lblSale_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Manager.
        /// </summary>
        public static string lblSale_Manager {
            get {
                return ResourceManager.GetString("lblSale_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale&apos;s Name.
        /// </summary>
        public static string lblSale_Name {
            get {
                return ResourceManager.GetString("lblSale_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to my email.
        /// </summary>
        public static string lblSent_myEmail {
            get {
                return ResourceManager.GetString("lblSent_myEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentbox.
        /// </summary>
        public static string lblSentbox {
            get {
                return ResourceManager.GetString("lblSentbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone wants.
        /// </summary>
        public static string lblSomeoneWants {
            get {
                return ResourceManager.GetString("lblSomeoneWants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string lblSum {
            get {
                return ResourceManager.GetString("lblSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last product with the purchase price..
        /// </summary>
        public static string lblTitleBidList {
            get {
                return ResourceManager.GetString("lblTitleBidList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string lblTotal_Price {
            get {
                return ResourceManager.GetString("lblTotal_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string lblTotalAmount {
            get {
                return ResourceManager.GetString("lblTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat (%).
        /// </summary>
        public static string lblVat {
            get {
                return ResourceManager.GetString("lblVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With buyer.
        /// </summary>
        public static string lblWithBuyer {
            get {
                return ResourceManager.GetString("lblWithBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, contact my personal e-mail..
        /// </summary>
        public static string lblwouldEmail {
            get {
                return ResourceManager.GetString("lblwouldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, contact by telephone..
        /// </summary>
        public static string lblwouldPhone {
            get {
                return ResourceManager.GetString("lblwouldPhone", resourceCulture);
            }
        }
    }
}
