//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prosoft.Resource.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prosoft.Resource.Web.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection is success.
        /// </summary>
        public static string lblConnectionSuccess {
            get {
                return ResourceManager.GetString("lblConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Save This Item.
        /// </summary>
        public static string lblConnotSave {
            get {
                return ResourceManager.GetString("lblConnotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string lblCreate {
            get {
                return ResourceManager.GetString("lblCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string lblHelp {
            get {
                return ResourceManager.GetString("lblHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print.
        /// </summary>
        public static string lblPrint {
            get {
                return ResourceManager.GetString("lblPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save success.
        /// </summary>
        public static string lblSaveSuccess {
            get {
                return ResourceManager.GetString("lblSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message Success..
        /// </summary>
        public static string lblSendMsgSuccess {
            get {
                return ResourceManager.GetString("lblSendMsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setting.
        /// </summary>
        public static string lblSetting {
            get {
                return ResourceManager.GetString("lblSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string lblSignIn {
            get {
                return ResourceManager.GetString("lblSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string lblSignOut {
            get {
                return ResourceManager.GetString("lblSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        public static string lblSignUp {
            get {
                return ResourceManager.GetString("lblSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Connect Database.
        /// </summary>
        public static string vldCannotConnectDB {
            get {
                return ResourceManager.GetString("vldCannotConnectDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Sent Mail.
        /// </summary>
        public static string vldCannotSendMail {
            get {
                return ResourceManager.GetString("vldCannotSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect database..
        /// </summary>
        public static string vldRequired {
            get {
                return ResourceManager.GetString("vldRequired", resourceCulture);
            }
        }
    }
}
